# Form implementation generated from reading ui file '/home/donald/src/wish/wish/licenses.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LicensesDialog(object):
    def setupUi(self, LicensesDialog):
        LicensesDialog.setObjectName("LicensesDialog")
        LicensesDialog.resize(560, 520)
        LicensesDialog.setMinimumSize(QtCore.QSize(360, 280))
        LicensesDialog.setSizeGripEnabled(True)
        self.outer_layout = QtWidgets.QVBoxLayout(LicensesDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.content = QtWidgets.QTextBrowser(parent=LicensesDialog)
        self.content.setReadOnly(True)
        self.content.setObjectName("content")
        self.outer_layout.addWidget(self.content)
        self.buttons = QtWidgets.QDialogButtonBox(parent=LicensesDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)

        self.retranslateUi(LicensesDialog)
        self.buttons.rejected.connect(LicensesDialog.reject) # type: ignore
        self.buttons.accepted.connect(LicensesDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LicensesDialog)

    def retranslateUi(self, LicensesDialog):
        _translate = QtCore.QCoreApplication.translate
        LicensesDialog.setWindowTitle(_translate("LicensesDialog", "Licenses"))
