# Form implementation generated from reading ui file 'wish/preferences.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.setModal(True)
        self.outer_layout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.tabs = QtWidgets.QTabWidget(parent=PreferencesDialog)
        self.tabs.setObjectName("tabs")
        self.general_scroll_page = QtWidgets.QWidget()
        self.general_scroll_page.setObjectName("general_scroll_page")
        self.tabs.addTab(self.general_scroll_page, "")
        self.travel_page = QtWidgets.QWidget()
        self.travel_page.setObjectName("travel_page")
        self.tabs.addTab(self.travel_page, "")
        self.outer_layout.addWidget(self.tabs)
        self.buttons = QtWidgets.QDialogButtonBox(parent=PreferencesDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)

        self.retranslateUi(PreferencesDialog)
        self.tabs.setCurrentIndex(0)
        self.buttons.rejected.connect(PreferencesDialog.reject) # type: ignore
        self.buttons.accepted.connect(PreferencesDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.tabs.setTabText(self.tabs.indexOf(self.general_scroll_page), _translate("PreferencesDialog", "General"))
        self.tabs.setTabText(self.tabs.indexOf(self.travel_page), _translate("PreferencesDialog", "Fast travel"))
