# Form implementation generated from reading ui file '/home/donald/src/wish/wish/window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_WishWindow(object):
    def setupUi(self, WishWindow):
        WishWindow.setObjectName("WishWindow")
        self.centralwidget = QtWidgets.QWidget(parent=WishWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.central_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.central_layout.setContentsMargins(0, 0, 0, 0)
        self.central_layout.setObjectName("central_layout")
        self.tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.central_layout.addWidget(self.tabs)
        WishWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=WishWindow)
        self.statusbar.setObjectName("statusbar")
        WishWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WishWindow)
        QtCore.QMetaObject.connectSlotsByName(WishWindow)

    def retranslateUi(self, WishWindow):
        _translate = QtCore.QCoreApplication.translate
        WishWindow.setWindowTitle(_translate("WishWindow", "Wish"))
