"""`tools/c64/creation.py` against a scripted game: no emulator, no display.

The fake is a small state machine of the creation screens of C64 Pool of
Radiance -- the roll before the class, the ADD list that stays up, the drive
that only shows its directory after a re-attach -- and the driver under test is
the real one, calling the real `Session.select_row` and `Session.select_bar`
against it.  Its `disk3` screen is a guess, not a measured one.  Records are generated by
`tools/suite/testparty.py`, never read from game data.
"""

import json
import pathlib

import pytest
from conftest import load_tools_module

from automap.screen import Screen
from goldbox import c64_port, savegame
from goldbox.d64 import D64

creation = load_tools_module("creation")
testparty = load_tools_module("testparty")
S = creation.S

GAME = c64_port.by_key("pool-of-radiance")

CLASSES = {
    "DWARF": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "ELF": ["FIGHTER", "MAGIC-USER", "THIEF", "FIGHTER/MAGIC-USER",
            "FIGHTER/THIEF", "FIGHTER/MAGIC-USER/THIEF", "MAGIC-USER/THIEF"],
    "GNOME": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "HALF-ELF": ["CLERIC", "FIGHTER", "MAGIC-USER", "THIEF", "CLERIC/FIGHTER",
                 "CLERIC/FIGHTER/MAGIC-USER", "CLERIC/MAGIC-USER",
                 "FIGHTER/MAGIC-USER", "FIGHTER/THIEF",
                 "FIGHTER/MAGIC-USER/THIEF", "MAGIC-USER/THIEF"],
    "HALFLING": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "HUMAN": ["CLERIC", "FIGHTER", "MAGIC-USER", "THIEF"],
}
ROLLS = [
    dict(strength=17, intelligence=16, wisdom=15, dexterity=14,
         constitution=16, charisma=13),
    dict(strength=12, intelligence=15, wisdom=10, dexterity=13,
         constitution=11, charisma=9),
    dict(strength=10, intelligence=11, wisdom=12, dexterity=15,
         constitution=14, charisma=8),
]


def spec(name="VICEFTR", race="HUMAN", gender="MALE", cls="FIGHTER",
         alignment="LAWFUL GOOD"):
    return creation.Spec.from_json({"name": name, "race": race,
                                    "gender": gender, "class": cls,
                                    "alignment": alignment})


def record(sp, roll, exceptional=0):
    """What the engine would have written for SP, generated by `testparty`."""
    one = testparty.build(testparty.Spec(
        name=sp.name, race=creation.RACES[sp.race],
        sex=creation.GENDERS[sp.gender], levels=dict(sp.classes),
        abilities=dict(roll), alignment=creation.ALIGNMENTS.index(sp.alignment),
        age=20, experience=0, portrait=(0, 1)))
    if exceptional:
        one.record.set("exceptional_strength", exceptional)
    return one.record


def disk(records, party=False, exports=True, names=None, camp=False):
    """A save disk: the `\\x01NAME` exports, and SAVEDGAME0 once saved.
    `names` are the file names when they differ from the records' own; `camp`
    makes the SAVEDGAME0 differ from a party-menu save's."""
    image = D64.blank()
    if exports:
        for rec, name in zip(records, names or [r.name for r in records]):
            image.write_file(b"\x01" + name.encode(), rec.to_prg())
    if party:
        sg0 = savegame.SaveGame0(bytes(GAME.save_size), GAME)
        for i, rec in enumerate(records):
            sg0.write_record(i, rec)
        prg = bytearray(sg0.to_prg())
        if camp:
            prg[-1] ^= 1
        image.write_file(b"SAVEDGAME0", bytes(prg))
    return image


def write_disks(tmp, records, names=None):
    """The two disks a build leaves: exports before the add, slots after."""
    disk(records, names=names).save(str(tmp / "rolled.D64"))
    disk(records, party=True, exports=False).save(str(tmp / "party.D64"))


# -- the scripted game ---------------------------------------------------------


COLS = 40


def encode(ch):
    if ch == "@":
        return 0
    if "A" <= ch <= "Z":
        return ord(ch) - 64
    return ord(ch)


class FakeKeyboard:
    def __init__(self, game):
        self.game, self.sent = game, []

    def key(self, name, hold=0.0, gap=0.0):
        self.sent.append((self.game.state, name))
        self.game.key(name)

    def text(self, s, hold=0.0, gap=0.0):
        self.sent.append((self.game.state, "text " + s))
        self.game.typed += s.upper()

    def screenshot(self, path, **_kw):
        pathlib.Path(path).write_bytes(b"png")
        return True


class FakeGame:
    """The screens of CREATE NEW CHARACTER, ADD and SAVE, one state each."""

    PARTY_EMPTY = ["CREATE NEW CHARACTER", "ADD CHARACTER TO PARTY",
                   "LOAD SAVED GAME"]
    PARTY_FULL = ["CREATE NEW CHARACTER", "DROP CHARACTER", "MODIFY CHARACTER",
                  "VIEW CHARACTER", "ADD CHARACTER TO PARTY",
                  "REMOVE CHARACTER FROM PARTY", "SAVE CURRENT GAME",
                  "BEGIN ADVENTURING"]

    def __init__(self, tmp, rolls=ROLLS, add_closes=False, stall=None,
                 start="party", lose_first=None, slow=None, trim=()):
        """`stall`: a state whose keys do nothing.  `lose_first`: a state whose
        first Return is dropped.  `slow`: state -> (polls, redraws), a Return
        that is accepted but takes that many screen reads to show its result,
        the screen redrawn meanwhile or left as it was.  `trim`: class labels
        the roll does not qualify for, left off the class list."""
        self.trim = tuple(trim)
        self.tmp, self.rolls = tmp, list(rolls)
        self.add_closes, self.stall = add_closes, stall
        self.lose_first, self.slow = lose_first, dict(slow or {})
        self.delayed = None             # [polls left, state the key was sent in]
        self.camped = False
        self.state, self.cursor, self.typed = start, 0, ""
        self.rolled = 0
        self.roll = {}
        self.pick = {}
        self.created: list = []      # (spec-ish dict, roll) in memory
        self.added: list[str] = []
        self.on_disk_created: list = []
        self.saved = False
        self.saving_polls = 0
        self.chosen: list[tuple[str, str]] = []
        self.save_disk = str(tmp / "SIDE0.D64")
        D64.blank().save(self.save_disk)

    # -- what is on each screen ---------------------------------------------

    def items(self):
        s = self.state
        if s == "party":
            return self.PARTY_FULL if self.added else self.PARTY_EMPTY
        if s == "race":
            return list(creation.RACES) + ["EXIT"]
        if s == "gender":
            return list(creation.GENDERS)
        if s == "roll":
            return ["ROLL AGAIN", "KEEP"]
        if s == "class":
            return [c for c in CLASSES[self.pick["race"]] if c not in self.trim]
        if s == "align":
            aligns = list(creation.ALIGNMENTS)
            if "CLERIC" in self.pick["class"]:
                aligns.remove("TRUE NEUTRAL")
            if "THIEF" in self.pick["class"]:
                aligns = [a for a in aligns
                          if a not in ("LAWFUL GOOD", "CHAOTIC GOOD")]
            return aligns
        if s == "sheet":
            return ["YES", "NO"]
        if s == "add":
            return [c["name"] for c in self.created] + ["EXIT"]
        return []

    def render(self):
        codes = bytearray(0x20 for _ in range(25 * COLS))
        colours = bytearray(5 for _ in range(25 * COLS))

        def put(row, col, text, hot=False):
            for i, ch in enumerate(text):
                codes[row * COLS + col + i] = encode(ch)
                if hot:
                    colours[row * COLS + col + i] = 1

        s, items = self.state, self.items()

        def listing(prompt, col, first=2, whole_row=False):
            for i, label in enumerate(items):
                hot = i == self.cursor
                put(first + i, col, label, hot)
                if hot and whole_row:
                    for c in range(1, 39):
                        colours[(first + i) * COLS + c] = 1
            put(first + len(items) + 1, 2, prompt)

        if s == "party":
            for i, label in enumerate(items):
                put(13 + i, 2, label, i == self.cursor)
        elif s == "race":
            listing("PICK RACE", 2)
        elif s == "gender":
            listing("PICK GENDER", 2)
        elif s == "roll":
            put(5, 2, f"RACE {self.pick['race']}")
            for i, (k, v) in enumerate(self.roll.items()):
                put(6 + i, 2, f"{k.upper()} {v}")
            for i, label in enumerate(items):
                put(12 + i, 2, label, i == self.cursor)
        elif s == "class":
            listing("PICK CLASS", 1, whole_row=True)
        elif s == "align":
            listing("PICK ALIGNMENT", 2)
        elif s == "name":
            put(2, 2, "INPUT NAME OF CHARACTER")
            put(3, 2, self.typed.lower().upper())
        elif s == "sheet":
            put(13, 28, "SAVE?")
            for i, label in enumerate(items):
                put(15 + i, 28, label, i == self.cursor)
        elif s == "disk3":
            # Unmeasured: this prompt after a second character's sheet is a
            # guess from the loader's code.
            put(18, 2, "INSERT GAME DISK #3")
            put(24, 0, "PRESS ANY KEY TO CONTINUE")
        elif s in ("portrait", "icon", "save_yn"):
            bar = {"portrait": ["CHANGE:HEAD", "BODY", "KEEP"],
                   "icon": ["ICON:PARTS", "COLOR", "SIZE", "EXIT"],
                   "save_yn": ["SAVE GAME: YES", "NO"]}[s]
            col = 0
            for i, word in enumerate(bar):
                label = word.split(":")[-1].split(" ")[-1]
                put(24, col, word + " ")
                start = col + len(word) - len(label)
                if i == self.cursor:
                    put(24, start, label, True)
                col += len(word) + 1
        elif s == "diskprompt":
            put(24, 0, "INSERT YOUR SAVE GAME DISK")
        elif s == "add":
            for i, label in enumerate(items):
                star = "*" if label in self.added else " "
                put(2 + i, 3, star)
                put(2 + i, 4, label, i == self.cursor)
            put(2 + len(items) + 2, 2, "ADD CHARACTER TO PARTY")
        elif s == "saving":
            put(10, 2, "SAVING GAME")
            for i, label in enumerate(self.PARTY_FULL):
                put(13 + i, 2, label)
        elif s == "junk":
            put(5, 5, "A SCREEN NOBODY DRAWS")
        if self.delayed and self.slow[self.delayed[1]][1]:
            put(22, 5, "LOADING")     # the screen changes, not to the next one
        return Screen(bytes(codes), bytes(colours), 0x0400)

    def bar_words(self):
        return {"portrait": ["HEAD", "BODY", "KEEP"],
                "icon": ["PARTS", "COLOR", "SIZE", "EXIT"],
                "save_yn": ["YES", "NO"]}[self.state]

    # -- what a key does ----------------------------------------------------

    def new_roll(self):
        self.roll = dict(self.rolls[self.rolled % len(self.rolls)])
        self.rolled += 1

    def go(self, state):
        self.state, self.cursor = state, 0

    def key(self, name):
        if self.stall == self.state or self.delayed:
            return
        if name == "Return" and self.lose_first == self.state:
            self.lose_first = None
            return
        if name == "Return" and self.state in self.slow:
            self.delayed = [self.slow[self.state][0], self.state]
            return
        s = self.state
        if name in ("Down", "Right"):
            n = len(self.bar_words() if s in ("portrait", "icon", "save_yn")
                    else self.items())
            self.cursor = min(self.cursor + 1, n - 1)
        elif name in ("Up", "Left"):
            self.cursor = max(self.cursor - 1, 0)
        elif name == "space":
            if s == "diskprompt":
                self.write()
            elif s == "disk3":
                self.go("portrait")
        elif name == "Return":
            self.enter()

    def enter(self):
        s = self.state
        words = (self.bar_words() if s in ("portrait", "icon", "save_yn")
                 else self.items())
        label = words[self.cursor] if words else ""
        self.chosen.append((s, label))
        if s == "party":
            self.go({"CREATE NEW CHARACTER": "race",
                     "ADD CHARACTER TO PARTY": "add",
                     "SAVE CURRENT GAME": "save_yn",
                     "BEGIN ADVENTURING": "world"}[label])
        elif s == "race":
            if label == "EXIT":
                self.go("party")
            else:
                self.pick["race"] = label
                self.go("gender")
        elif s == "gender":
            self.pick["gender"] = label
            self.new_roll()
            self.go("roll")
        elif s == "roll":
            if label == "KEEP":
                self.go("class")
            else:
                self.new_roll()
        elif s == "class":
            self.pick["class"] = label
            self.go("align")
        elif s == "align":
            self.pick["alignment"] = label
            self.typed = ""
            self.go("name")
        elif s == "name":
            if self.typed:
                self.pick["name"] = self.typed
                self.go("sheet")
        elif s == "sheet":
            self.go("disk3" if self.created else "portrait")
        elif s == "portrait" and label == "KEEP":
            self.go("icon")
        elif s == "icon" and label == "EXIT":
            self.go("diskprompt")
        elif s == "add":
            if label == "EXIT":
                self.go("party")
            else:
                self.added.append(label)
                if self.add_closes and len(self.added) == len(self.created):
                    self.go("party")
        elif s == "save_yn":
            if label == "YES":
                self.saving_polls = 2
                self.go("saving")

    def back(self):
        s = self.state
        if s == "align":
            self.go("class")
        elif s == "class":
            self.new_roll()
            self.go("roll")
        elif s == "roll":
            self.go("gender")
        elif s == "gender":
            self.go("race")

    def write(self):
        self.created.append({**self.pick, "roll": dict(self.roll)})
        self.go("race")

    def tick(self):
        """One read of the screen: the write to the disk runs on."""
        if self.delayed:
            self.delayed[0] -= 1
            if self.delayed[0] <= 0:
                self.delayed = None
                self.enter()
        if self.state == "saving" and self.stall != "saving":
            self.saving_polls -= 1
            if self.saving_polls <= 0:
                self.saved = True
                self.go("party")
                self.cursor = 6

    def flush(self):
        """The drive shows its directory only once the head has moved."""
        records = []
        for c in self.created:
            sp = spec(c["name"], c["race"], c["gender"], c["class"],
                      c["alignment"])
            records.append(record(sp, c["roll"]))
        disk(records, party=self.saved, camp=self.camped).save(self.save_disk)


class FakeSession(S.Session):
    """A `Session` whose screen and keyboard are the scripted game."""

    def __init__(self, game):
        self.script = game
        self.kbd = FakeKeyboard(game)
        self.here = str(game.tmp)
        self.save_disk = game.save_disk
        self.attached = "SIDE1.D64"
        self.attaches: list[str] = []
        self.kernal: list[int] = []
        self.world_timeouts: list[float] = []
        self.camp_saves = 0
        self.camp_lands = True
        self.camp_wipes = False
        self.world_arrives = True

    def screen(self):
        self.script.tick()
        if self.script.state == "world":
            return None
        return self.script.render()

    def attach(self, path, unit=8, settle=None):
        self.attaches.append(pathlib.Path(path).name)
        if pathlib.Path(path) == pathlib.Path(self.script.save_disk):
            self.script.flush()

    def handle_prompt(self, s=None):
        want = self.wanted_disk(s if s is not None else self.screen())
        if want is None:
            return False
        self.attach(want)
        self.kbd.key("space")
        return True

    def press_kernal(self, code):
        self.kernal.append(code)
        if code == 0x5F:
            self.script.back()

    def wait_for_world(self, timeout=240.0, interval=0.35):
        self.world_timeouts.append(timeout)
        return self.world_arrives

    def save_game(self, to=None):
        self.camp_saves += 1
        self.script.camped = self.camp_lands
        self.script.flush()
        if self.camp_wipes:
            D64.blank().save(self.script.save_disk)
        return True


class Clock:
    def __init__(self):
        self.now = 0.0

    def __call__(self):
        return self.now

    def sleep(self, seconds):
        self.now += seconds


def drive(tmp, specs, game=None, **kw):
    game = game or FakeGame(tmp)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp / "run"
    code = creation.run(sess, out, specs=specs, clock=clock,
                        sleep=clock.sleep, **kw)
    return code, sess, game, out, json.loads((out / "summary.json").read_text())


PAIR = [spec("VICEFTR", "HUMAN", "MALE", "FIGHTER", "LAWFUL GOOD"),
        spec("VICEDWF", "DWARF", "FEMALE", "FIGHTER/THIEF", "LAWFUL NEUTRAL")]


# -- the driver ------------------------------------------------------------------


def test_every_spec_entry_is_selected_by_its_label(tmp_path):
    """Each character's race, gender, class and alignment are taken by name
    off their own lists, the roll is kept by moving to KEEP rather than by
    pressing Return on the screen's first row, and the records read back match.
    """
    code, sess, game, out, summary = drive(tmp_path, PAIR)
    assert summary["lost"] is None and summary["completed"] is True and code == 0
    picked = [(s, lab) for s, lab in game.chosen if s not in ("party", "name")]
    assert picked[:6] == [("race", "HUMAN"), ("gender", "MALE"),
                          ("roll", "KEEP"), ("class", "FIGHTER"),
                          ("align", "LAWFUL GOOD"), ("sheet", "YES")]
    assert ("race", "DWARF") in picked and ("gender", "FEMALE") in picked
    assert ("class", "FIGHTER/THIEF") in picked
    assert ("align", "LAWFUL NEUTRAL") in picked
    assert ("roll", "ROLL AGAIN") not in picked
    assert (out / "records.txt").read_text().splitlines()[-1] \
        == "all records match the spec"
    assert {p.name for p in out.glob("*.D64")} >= {"rolled.D64", "party.D64"}
    assert list((out / "shots").glob("*.txt"))
    lines = [json.loads(ln) for ln in (out / "run.jsonl").read_text().splitlines()]
    assert [ln["strength"] for ln in lines if ln["kind"] == "roll"] == [17, 12]


def test_the_save_disk_is_reattached_before_each_copy(tmp_path):
    """The drive shows its directory only after the head moves, so a copy
    taken without a re-attach holds no characters: both disks must name them."""
    code, sess, game, out, summary = drive(tmp_path, PAIR)
    assert code == 0
    assert sess.attaches.count("SIDE0.D64") >= 2
    exports = D64.open(str(out / "rolled.D64"))
    for name in (b"\x01VICEFTR", b"\x01VICEDWF"):
        assert len(exports.read_file(name)) == 582


def test_a_class_the_race_is_never_offered_is_refused_before_any_key(tmp_path):
    """No magic-user in a dwarf's class list: the refusal comes before the
    first character is created, even when the dwarf is the second spec."""
    dwarf = spec("VICEMAG", "DWARF", "MALE", "MAGIC-USER", "LAWFUL GOOD")
    code, sess, game, out, summary = drive(tmp_path, [PAIR[0], dwarf])
    assert code == 1 and "a DWARF is never offered MAGIC-USER" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == [] and sess.attaches == []


@pytest.mark.parametrize("cls, alignment", [
    ("THIEF", "LAWFUL GOOD"), ("THIEF", "CHAOTIC GOOD"),
    ("FIGHTER/THIEF", "LAWFUL GOOD"), ("CLERIC", "TRUE NEUTRAL"),
    ("CLERIC/FIGHTER", "TRUE NEUTRAL")])
def test_an_alignment_the_class_is_never_offered_is_refused_before_any_key(
        tmp_path, cls, alignment):
    bad = spec("VICEBAD", "HALF-ELF", "MALE", cls, alignment)
    code, sess, game, out, summary = drive(tmp_path, [PAIR[0], bad])
    assert code == 1 and f"{cls} is never offered {alignment}" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == [] and sess.attaches == []


def test_the_alignment_table_is_the_lists_the_screens_draw(tmp_path):
    """Every class a list offers, opened on the fake, against the table."""
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    assert creation.run(sess, out, lists=True, clock=clock,
                        sleep=clock.sleep) == 0
    found = json.loads((out / "lists.json").read_text())["alignments"]
    assert "CLERIC" in found and "FIGHTER/THIEF" in found
    assert {c: tuple(a) for c, a in found.items()} \
        == {c: creation.alignments_offered(c) for c in found}


def test_a_roll_that_trims_the_class_list_stops_on_that_screen(tmp_path):
    """The roll, not the race, drops THIEF: only the screen can say so, and the
    run stops there sending neither an arrow nor Return."""
    game = FakeGame(tmp_path, trim=("THIEF",))
    thief = spec("VICETHI", "HUMAN", "MALE", "THIEF", "LAWFUL NEUTRAL")
    code, sess, game, out, summary = drive(tmp_path, [thief], game)
    assert code == 1 and "THIEF is not in the class list" in summary["lost"]
    assert game.state == "class"
    assert [k for state, k in sess.kbd.sent if state == "class"] == []
    assert list((out / "shots").glob("*lost-label.txt"))


SHADOWED = [("ELF", "MAGIC-USER/THIEF", "FIGHTER/MAGIC-USER/THIEF"),
            ("HALF-ELF", "MAGIC-USER/THIEF", "FIGHTER/MAGIC-USER/THIEF"),
            ("HALF-ELF", "FIGHTER/MAGIC-USER", "CLERIC/FIGHTER/MAGIC-USER")]


@pytest.mark.parametrize("race, cls, earlier", SHADOWED)
def test_a_class_that_is_the_tail_of_a_longer_row_is_accepted_and_selected(
        tmp_path, race, cls, earlier):
    """The class rows are bare labels and are matched whole, so the class is not
    mistaken for the longer row above it."""
    want = spec("VICEEXA", race, "MALE", cls, "LAWFUL NEUTRAL")
    creation.check_specs([want])
    code, sess, game, out, summary = drive(tmp_path, [want])
    assert code == 0 and summary["lost"] is None
    assert ("class", cls) in game.chosen
    assert ("class", earlier) not in game.chosen


def test_the_class_table_is_the_lists_the_screens_draw():
    assert {r: list(c) for r, c in creation.CLASSES_BY_RACE.items()} == CLASSES


@pytest.mark.parametrize("specs, why", [
    ([], "names no characters"),
    ([PAIR[0], PAIR[0]], "a name is used twice"),
    ([spec("VICE"), spec("VICEFTR")], "part of another name"),
])
def test_a_party_the_driver_cannot_build_is_refused_before_any_key(
        tmp_path, specs, why):
    code, sess, _game, _out, summary = drive(tmp_path, specs)
    assert code == 1 and why in summary["lost"] and sess.kbd.sent == []


def test_an_unrecognised_screen_stops_with_a_capture_and_no_key(tmp_path, monkeypatch):
    monkeypatch.setattr(creation, "UNRECOGNISED_SECONDS", 5.0)
    game = FakeGame(tmp_path, start="junk")
    code, sess, game, out, summary = drive(tmp_path, PAIR, game)
    assert code == 1 and "an unrecognised screen" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == []
    shot = next((out / "shots").glob("*lost-unrecognised.txt"))
    assert "A SCREEN NOBODY DRAWS" in shot.read_text()


def test_the_add_list_gets_exit_only_while_it_is_still_up(tmp_path):
    """The list stays up after the last add on the C64, so EXIT leaves it; a
    list that had closed itself is not pressed at."""
    code, _sess, game, _out, _s = drive(tmp_path, PAIR)
    assert code == 0
    assert [lab for st, lab in game.chosen if st == "add"] \
        == ["VICEFTR", "VICEDWF", "EXIT"]

    code, _sess, closing, _out, _s = drive(
        tmp_path / "closing", PAIR,
        FakeGame(_mkdir(tmp_path / "closing"), add_closes=True))
    assert code == 0
    assert [lab for st, lab in closing.chosen if st == "add"] \
        == ["VICEFTR", "VICEDWF"]
    assert ("party", "EXIT") not in closing.chosen


def _mkdir(p):
    p.mkdir()
    return p


def test_a_deadline_passing_mid_step_writes_lost_to_the_summary(tmp_path):
    """The write never finishes: the run stops at its own deadline, keeps the
    screen it was looking at, and says so in `summary.json`."""
    game = FakeGame(tmp_path, stall="saving")
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR[:1], max_seconds=200.0,
                        clock=clock, sleep=clock.sleep)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and summary["completed"] is False
    assert "seconds were spent" in summary["lost"]
    assert clock.now < 200.0     # ended inside the cleanup window, not past it
    assert list((out / "shots").glob("*lost-deadline.txt"))


def test_enter_world_waits_with_its_own_budget_and_saves_the_camp(tmp_path):
    code, sess, game, out, summary = drive(tmp_path, PAIR, enter_world=True,
                                           world_budget=450.0)
    assert code == 0
    assert sess.world_timeouts == [450.0] and sess.camp_saves == 1
    assert ("party", "BEGIN ADVENTURING") in game.chosen
    assert (out / "intown.D64").is_file()


def test_the_summary_carries_the_evidence_keys(tmp_path):
    _code, _sess, _game, out, summary = drive(
        tmp_path, PAIR, git={"sha": "abc", "dirty": []}, argv=["--build", "x"])
    assert {"sha", "dirty", "argv", "completed", "lost"} <= set(summary)
    assert summary["argv"] == ["--build", "x"]


def test_a_key_that_did_nothing_is_sent_once_more(tmp_path):
    """The first Return on the gender list is lost and the screen does not
    change, so exactly one resend follows."""
    game = FakeGame(tmp_path, lose_first="gender")
    code, sess, _game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert code == 0, summary["lost"]
    assert [k for st, k in sess.kbd.sent if st == "gender"] == ["Return", "Return"]


def test_a_slow_key_is_not_sent_again(tmp_path):
    """A Return that is taken but whose result takes 15 s, the screen redrawn
    meanwhile, is sent once: only a screen identical to the one before the key
    counts as a key that did nothing."""
    game = FakeGame(tmp_path, slow={"gender": (30, True)})
    code, sess, _game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert code == 0, summary["lost"]
    assert [k for st, k in sess.kbd.sent if st == "gender"] == ["Return"]


def test_create_new_character_is_never_sent_twice(tmp_path):
    """Its overlay takes 3.4-12 s to draw with the party menu still showing,
    longer than the resend window, so a resend would land on PICK RACE."""
    game = FakeGame(tmp_path, slow={"party": (30, False)})
    code, sess, _game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert code == 0, summary["lost"]
    first = next(i for i, (st, _k) in enumerate(sess.kbd.sent) if st != "party")
    assert [k for _st, k in sess.kbd.sent[:first]] == ["Return"]


def test_a_camp_save_that_did_not_land_is_lost(tmp_path):
    """`save_game` returns True whether or not the disk changed."""
    sess_game = FakeGame(tmp_path)
    sess = FakeSession(sess_game)
    sess.camp_lands = False
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR, clock=clock, sleep=clock.sleep,
                        enter_world=True)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and "camp save did not land" in summary["lost"]


def test_a_camp_save_that_wrote_no_savegame_is_lost(tmp_path):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    sess.camp_wipes = True
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR, clock=clock, sleep=clock.sleep,
                        enter_world=True)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and "intown.D64 holds no SAVEDGAME0" in summary["lost"]


def test_records_are_checked_before_the_world_is_entered(tmp_path):
    """A world that never arrives still leaves `records.txt`."""
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    sess.world_arrives = False
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR, clock=clock, sleep=clock.sleep,
                        enter_world=True)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and "world bar did not come" in summary["lost"]
    assert (out / "records.txt").read_text().splitlines()[-1] \
        == "all records match the spec"


@pytest.mark.parametrize("name", ["EYES", "VICEYESX", "EXITER", "NEXIT"])
def test_a_name_holding_a_menu_word_is_refused(name):
    with pytest.raises(ValueError, match="menu"):
        spec(name)


def test_a_stop_before_the_run_still_leaves_a_summary(tmp_path, monkeypatch):
    """Staging raises before `run` is reached; `main` still writes one."""
    class Slot:
        dir = str(tmp_path / "slot")

        def teardown(self):
            pass

        def release(self):
            pass

    out = tmp_path / "evidence"
    monkeypatch.setattr(creation.S, "claim_slot", lambda *a, **k: Slot())

    def boom(*_a, **_k):
        raise RuntimeError("no disks to stage")
    monkeypatch.setattr(creation.S, "stage_disks", boom)
    monkeypatch.setattr(creation.evidence, "default_out", lambda *a, **k: out)
    monkeypatch.setattr(creation.runlog, "catch_signals", lambda: None)
    with pytest.raises(RuntimeError):
        creation.main(["--lists", "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    summary = json.loads((out / "summary.json").read_text())
    assert summary["completed"] is False and "no disks to stage" in summary["lost"]


class Slot:
    def __init__(self, tmp):
        self.dir = str(tmp / "slot")
        self.calls = []

    def teardown(self):
        self.calls.append("teardown")

    def release(self):
        self.calls.append("release")


def stage_main(tmp_path, monkeypatch, slot=None):
    """`main` with the pool, the evidence directory and the signals replaced."""
    out = tmp_path / "evidence"
    monkeypatch.setattr(creation.S, "claim_slot", lambda *a, **k: slot)
    monkeypatch.setattr(creation.evidence, "default_out", lambda *a, **k: out)
    monkeypatch.setattr(creation.runlog, "catch_signals", lambda: None)
    return out


def test_a_refused_spec_leaves_a_summary_and_claims_no_slot(tmp_path, monkeypatch):
    def claim(*_a, **_k):
        raise AssertionError("a slot was claimed for a refused party")
    out = stage_main(tmp_path, monkeypatch)
    monkeypatch.setattr(creation.S, "claim_slot", claim)
    bad = tmp_path / "bad.json"
    bad.write_text(json.dumps([{"name": "VICEMAG", "race": "DWARF",
                                "gender": "MALE", "class": "MAGIC-USER",
                                "alignment": "LAWFUL GOOD"}]))
    with pytest.raises(SystemExit, match="never offered MAGIC-USER"):
        creation.main(["--build", str(bad), "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    summary = json.loads((out / "summary.json").read_text())
    assert summary["completed"] is False
    assert "never offered MAGIC-USER" in summary["lost"]


def test_a_full_pool_leaves_a_summary(tmp_path, monkeypatch):
    out = stage_main(tmp_path, monkeypatch)

    def full(*_a, **_k):
        raise RuntimeError("every slot is leased")
    monkeypatch.setattr(creation.S, "claim_slot", full)
    with pytest.raises(RuntimeError):
        creation.main(["--lists", "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    assert "every slot is leased" in \
        json.loads((out / "summary.json").read_text())["lost"]


def test_a_summary_that_cannot_be_written_still_releases_the_slot(
        tmp_path, monkeypatch):
    slot = Slot(tmp_path)
    stage_main(tmp_path, monkeypatch, slot)
    monkeypatch.setattr(creation.S, "stage_disks",
                        lambda *a, **k: (_ for _ in ()).throw(RuntimeError("x")))

    def cannot(*_a, **_k):
        raise OSError("disk full")
    monkeypatch.setattr(creation, "write_summary", cannot)
    with pytest.raises(OSError):
        creation.main(["--lists", "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    assert slot.calls == ["teardown", "release"]


def test_a_summary_that_cannot_be_written_still_closes_the_log(tmp_path, monkeypatch):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    closed = []
    real = creation.runlog.Log.close
    monkeypatch.setattr(creation.runlog.Log, "close",
                        lambda self: (closed.append(1), real(self))[1])

    def cannot(*_a, **_k):
        raise OSError("disk full")
    monkeypatch.setattr(creation, "write_summary", cannot)
    clock = Clock()
    with pytest.raises(OSError):
        creation.run(sess, tmp_path / "run", specs=PAIR, clock=clock,
                     sleep=clock.sleep)
    assert closed == [1]


# -- check_records ------------------------------------------------------------------


def checked(tmp_path, mutate=None, where="both", exceptional=0):
    """The records check on one character; MUTATE alters the record on the
    export, the slot or both, so each side is proved to be compared."""
    sp = PAIR[0]
    exported, slotted = (record(sp, ROLLS[0], exceptional) for _ in range(2))
    if mutate:
        if where in ("export", "both"):
            mutate(exported)
        if where in ("party", "both"):
            mutate(slotted)
    disk([exported], names=[sp.name]).save(str(tmp_path / "rolled.D64"))
    disk([slotted], party=True, exports=False).save(str(tmp_path / "party.D64"))
    return creation.check_records(tmp_path / "rolled.D64",
                                  tmp_path / "party.D64", [sp],
                                  {"VICEFTR": ROLLS[0]})


def test_matching_records_pass(tmp_path):
    assert checked(tmp_path)[-1] == "all records match the spec"


#: Every field `_expected` compares, with a value the spec does not ask for.
MUTATIONS = [
    ("name", "VICEFTX"), ("race", 2), ("sex", 1), ("alignment", 3),
    ("class_bits", 1), ("level_fighter", 2), ("level", 2), ("experience", 5),
    ("strength", 16), ("intelligence", 3), ("wisdom", 3), ("dexterity", 3),
    ("constitution", 3), ("charisma", 3),
]


@pytest.mark.parametrize("where", ["export", "party"])
@pytest.mark.parametrize("field, value", MUTATIONS)
def test_a_wrong_field_on_either_disk_is_rejected(tmp_path, field, value, where):
    lines = checked(tmp_path, lambda r: r.set(field, value), where)
    other = "party" if where == "export" else "export"
    assert lines[-1] == "SPEC MISMATCH"
    bad = [ln for ln in lines if f"VICEFTR {where}:" in ln]
    assert len(bad) == 1 and not bad[0].endswith("ok")
    assert [ln for ln in lines if f"VICEFTR {other}:" in ln][0].endswith("ok")


def test_every_compared_field_has_a_mutation():
    compared = set(creation._expected(PAIR[0], ROLLS[0]))
    covered = {"class_levels" if f == "level_fighter" else f for f, _ in MUTATIONS}
    assert compared == covered


def test_exceptional_strength_is_not_compared(tmp_path):
    """The roll screen never shows it: it is rolled after the alignment."""
    assert checked(tmp_path, exceptional=99)[-1] == "all records match the spec"


def test_a_character_with_no_roll_is_a_mismatch(tmp_path):
    checked(tmp_path)
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", PAIR[:1], {})
    assert lines[-1] == "SPEC MISMATCH" and "no roll was read" in lines[0]


def test_a_duplicate_name_is_a_mismatch(tmp_path):
    checked(tmp_path)
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", [PAIR[0], PAIR[0]],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "named twice" in lines[0]


def test_a_missing_export_is_a_mismatch(tmp_path):
    sp = PAIR[0]
    write_disks(tmp_path, [])
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", [sp],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "MISSING" in lines[0]
    assert "no such file" in lines[0]     # the read failure is shown, not hidden


@pytest.mark.parametrize("gone", ["rolled.D64", "party.D64"])
def test_a_disk_that_cannot_be_opened_is_a_mismatch_not_a_raise(tmp_path, gone):
    checked(tmp_path)
    (tmp_path / gone).unlink()
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", PAIR[:1],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH"
    assert f"{gone}: cannot be read" in lines[0] and "MISMATCH" in lines[0]


def test_a_party_disk_with_no_savegame_is_a_mismatch_not_a_raise(tmp_path):
    checked(tmp_path)
    D64.blank().save(str(tmp_path / "party.D64"))
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", PAIR[:1],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "party.D64: cannot be read" in lines[0]


@pytest.mark.parametrize("bad", [
    {"name": "TOO LONG A NAME FOR IT", "race": "HUMAN", "gender": "MALE",
     "class": "FIGHTER", "alignment": "LAWFUL GOOD"},
    {"name": "VICE", "race": "ORC", "gender": "MALE", "class": "FIGHTER",
     "alignment": "LAWFUL GOOD"},
    {"name": "VICE", "race": "HUMAN", "gender": "MALE", "class": "PALADIN",
     "alignment": "LAWFUL GOOD"},
])
def test_a_spec_the_screens_cannot_take_is_refused(bad):
    with pytest.raises(ValueError):
        creation.Spec.from_json(bad)


def test_lists_writes_every_races_classes_and_each_classs_alignments(tmp_path):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, lists=True, clock=clock, sleep=clock.sleep)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 0, summary["lost"]
    lists = json.loads((out / "lists.json").read_text())
    assert lists["classes"]["ELF"] == CLASSES["ELF"]
    assert "LAWFUL GOOD" not in lists["alignments"]["THIEF"]
    assert len(lists["alignments"]["FIGHTER"]) == 9
    assert lists["skipped"] == {}
    assert "LAWFUL GOOD" not in lists["alignments"]["MAGIC-USER/THIEF"]
    assert game.state == "party"
