"""`tools/c64/creation.py` against a scripted game: no emulator, no display.

The fake is a small state machine of the creation screens as they were measured
on a running C64 Pool of Radiance -- the roll before the class, the ADD list
that stays up, the drive that only shows its directory after a re-attach -- and
the driver under test is the real one, calling the real `Session.select_row`
and `Session.select_bar` against it.  Records are generated by
`tools/suite/testparty.py`, never read from game data.
"""

import json
import pathlib

import pytest
from conftest import load_tools_module

from automap.screen import Screen
from goldbox import c64_port, savegame
from goldbox.d64 import D64

creation = load_tools_module("creation")
testparty = load_tools_module("testparty")
S = creation.S

GAME = c64_port.by_key("pool-of-radiance")

CLASSES = {
    "DWARF": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "ELF": ["FIGHTER", "MAGIC-USER", "THIEF", "FIGHTER/MAGIC-USER",
            "FIGHTER/THIEF", "FIGHTER/MAGIC-USER/THIEF", "MAGIC-USER/THIEF"],
    "GNOME": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "HALF-ELF": ["CLERIC", "FIGHTER", "MAGIC-USER", "THIEF", "CLERIC/FIGHTER",
                 "CLERIC/FIGHTER/MAGIC-USER", "CLERIC/MAGIC-USER",
                 "FIGHTER/MAGIC-USER", "FIGHTER/THIEF",
                 "FIGHTER/MAGIC-USER/THIEF", "MAGIC-USER/THIEF"],
    "HALFLING": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "HUMAN": ["CLERIC", "FIGHTER", "MAGIC-USER", "THIEF"],
}
ROLLS = [
    dict(strength=17, intelligence=16, wisdom=15, dexterity=14,
         constitution=16, charisma=13),
    dict(strength=12, intelligence=15, wisdom=10, dexterity=13,
         constitution=11, charisma=9),
    dict(strength=10, intelligence=11, wisdom=12, dexterity=15,
         constitution=14, charisma=8),
]


def spec(name="VICEFTR", race="HUMAN", gender="MALE", cls="FIGHTER",
         alignment="LAWFUL GOOD"):
    return creation.Spec.from_json({"name": name, "race": race,
                                    "gender": gender, "class": cls,
                                    "alignment": alignment})


def record(sp, roll, exceptional=0):
    """What the engine would have written for SP, generated by `testparty`."""
    one = testparty.build(testparty.Spec(
        name=sp.name, race=creation.RACES[sp.race],
        sex=creation.GENDERS[sp.gender], levels=dict(sp.classes),
        abilities=dict(roll), alignment=creation.ALIGNMENTS.index(sp.alignment),
        age=20, experience=0, portrait=(0, 1)))
    if exceptional:
        one.record.set("exceptional_strength", exceptional)
    return one.record


def disk(records, party=False, exports=True, names=None):
    """A save disk: the `\\x01NAME` exports, and SAVEDGAME0 once saved.
    `names` are the file names when they differ from the records' own."""
    image = D64.blank()
    if exports:
        for rec, name in zip(records, names or [r.name for r in records]):
            image.write_file(b"\x01" + name.encode(), rec.to_prg())
    if party:
        sg0 = savegame.SaveGame0(bytes(GAME.save_size), GAME)
        for i, rec in enumerate(records):
            sg0.write_record(i, rec)
        image.write_file(b"SAVEDGAME0", sg0.to_prg())
    return image


def write_disks(tmp, records, names=None):
    """The two disks a build leaves: exports before the add, slots after."""
    disk(records, names=names).save(str(tmp / "rolled.D64"))
    disk(records, party=True, exports=False).save(str(tmp / "party.D64"))


# -- the scripted game ---------------------------------------------------------


COLS = 40


def encode(ch):
    if ch == "@":
        return 0
    if "A" <= ch <= "Z":
        return ord(ch) - 64
    return ord(ch)


class FakeKeyboard:
    def __init__(self, game):
        self.game, self.sent = game, []

    def key(self, name, hold=0.0, gap=0.0):
        self.sent.append((self.game.state, name))
        self.game.key(name)

    def text(self, s, hold=0.0, gap=0.0):
        self.sent.append((self.game.state, "text " + s))
        self.game.typed += s.upper()

    def screenshot(self, path, **_kw):
        pathlib.Path(path).write_bytes(b"png")
        return True


class FakeGame:
    """The screens of CREATE NEW CHARACTER, ADD and SAVE, one state each."""

    PARTY_EMPTY = ["CREATE NEW CHARACTER", "ADD CHARACTER TO PARTY",
                   "LOAD SAVED GAME"]
    PARTY_FULL = ["CREATE NEW CHARACTER", "DROP CHARACTER", "MODIFY CHARACTER",
                  "VIEW CHARACTER", "ADD CHARACTER TO PARTY",
                  "REMOVE CHARACTER FROM PARTY", "SAVE CURRENT GAME",
                  "BEGIN ADVENTURING"]

    def __init__(self, tmp, rolls=ROLLS, add_closes=False, stall=None,
                 start="party"):
        self.tmp, self.rolls = tmp, list(rolls)
        self.add_closes, self.stall = add_closes, stall
        self.state, self.cursor, self.typed = start, 0, ""
        self.rolled = 0
        self.roll = {}
        self.pick = {}
        self.created: list = []      # (spec-ish dict, roll) in memory
        self.added: list[str] = []
        self.on_disk_created: list = []
        self.saved = False
        self.saving_polls = 0
        self.chosen: list[tuple[str, str]] = []
        self.save_disk = str(tmp / "SIDE0.D64")
        D64.blank().save(self.save_disk)

    # -- what is on each screen ---------------------------------------------

    def items(self):
        s = self.state
        if s == "party":
            return self.PARTY_FULL if self.added else self.PARTY_EMPTY
        if s == "race":
            return list(creation.RACES) + ["EXIT"]
        if s == "gender":
            return list(creation.GENDERS)
        if s == "roll":
            return ["ROLL AGAIN", "KEEP"]
        if s == "class":
            return CLASSES[self.pick["race"]]
        if s == "align":
            aligns = list(creation.ALIGNMENTS)
            if "THIEF" in self.pick["class"]:
                aligns = [a for a in aligns
                          if a not in ("LAWFUL GOOD", "CHAOTIC GOOD")]
            return aligns
        if s == "sheet":
            return ["YES", "NO"]
        if s == "add":
            return [c["name"] for c in self.created] + ["EXIT"]
        return []

    def render(self):
        codes = bytearray(0x20 for _ in range(25 * COLS))
        colours = bytearray(5 for _ in range(25 * COLS))

        def put(row, col, text, hot=False):
            for i, ch in enumerate(text):
                codes[row * COLS + col + i] = encode(ch)
                if hot:
                    colours[row * COLS + col + i] = 1

        s, items = self.state, self.items()

        def listing(prompt, col, first=2, whole_row=False):
            for i, label in enumerate(items):
                hot = i == self.cursor
                put(first + i, col, label, hot)
                if hot and whole_row:
                    for c in range(1, 39):
                        colours[(first + i) * COLS + c] = 1
            put(first + len(items) + 1, 2, prompt)

        if s == "party":
            for i, label in enumerate(items):
                put(13 + i, 2, label, i == self.cursor)
        elif s == "race":
            listing("PICK RACE", 2)
        elif s == "gender":
            listing("PICK GENDER", 2)
        elif s == "roll":
            put(5, 2, f"RACE {self.pick['race']}")
            for i, (k, v) in enumerate(self.roll.items()):
                put(6 + i, 2, f"{k.upper()} {v}")
            for i, label in enumerate(items):
                put(12 + i, 2, label, i == self.cursor)
        elif s == "class":
            listing("PICK CLASS", 1, whole_row=True)
        elif s == "align":
            listing("PICK ALIGNMENT", 2)
        elif s == "name":
            put(2, 2, "INPUT NAME OF CHARACTER")
            put(3, 2, self.typed.lower().upper())
        elif s == "sheet":
            put(13, 28, "SAVE?")
            for i, label in enumerate(items):
                put(15 + i, 28, label, i == self.cursor)
        elif s == "disk3":
            put(18, 2, "INSERT GAME DISK #3")
            put(24, 0, "PRESS ANY KEY TO CONTINUE")
        elif s in ("portrait", "icon", "save_yn"):
            bar = {"portrait": ["CHANGE:HEAD", "BODY", "KEEP"],
                   "icon": ["ICON:PARTS", "COLOR", "SIZE", "EXIT"],
                   "save_yn": ["SAVE GAME: YES", "NO"]}[s]
            col = 0
            for i, word in enumerate(bar):
                label = word.split(":")[-1].split(" ")[-1]
                put(24, col, word + " ")
                start = col + len(word) - len(label)
                if i == self.cursor:
                    put(24, start, label, True)
                col += len(word) + 1
        elif s == "diskprompt":
            put(24, 0, "INSERT YOUR SAVE GAME DISK")
        elif s == "add":
            for i, label in enumerate(items):
                star = "*" if label in self.added else " "
                put(2 + i, 3, star)
                put(2 + i, 4, label, i == self.cursor)
            put(2 + len(items) + 2, 2, "ADD CHARACTER TO PARTY")
        elif s == "saving":
            put(10, 2, "SAVING GAME")
            for i, label in enumerate(self.PARTY_FULL):
                put(13 + i, 2, label)
        elif s == "junk":
            put(5, 5, "A SCREEN NOBODY DRAWS")
        return Screen(bytes(codes), bytes(colours), 0x0400)

    def bar_words(self):
        return {"portrait": ["HEAD", "BODY", "KEEP"],
                "icon": ["PARTS", "COLOR", "SIZE", "EXIT"],
                "save_yn": ["YES", "NO"]}[self.state]

    # -- what a key does ----------------------------------------------------

    def new_roll(self):
        self.roll = dict(self.rolls[self.rolled % len(self.rolls)])
        self.rolled += 1

    def go(self, state):
        self.state, self.cursor = state, 0

    def key(self, name):
        if self.stall == self.state:
            return
        s = self.state
        if name in ("Down", "Right"):
            n = len(self.bar_words() if s in ("portrait", "icon", "save_yn")
                    else self.items())
            self.cursor = min(self.cursor + 1, n - 1)
        elif name in ("Up", "Left"):
            self.cursor = max(self.cursor - 1, 0)
        elif name == "space":
            if s == "diskprompt":
                self.write()
            elif s == "disk3":
                self.go("portrait")
        elif name == "Return":
            self.enter()

    def enter(self):
        s = self.state
        words = (self.bar_words() if s in ("portrait", "icon", "save_yn")
                 else self.items())
        label = words[self.cursor] if words else ""
        self.chosen.append((s, label))
        if s == "party":
            self.go({"CREATE NEW CHARACTER": "race",
                     "ADD CHARACTER TO PARTY": "add",
                     "SAVE CURRENT GAME": "save_yn",
                     "BEGIN ADVENTURING": "world"}[label])
        elif s == "race":
            if label == "EXIT":
                self.go("party")
            else:
                self.pick["race"] = label
                self.go("gender")
        elif s == "gender":
            self.pick["gender"] = label
            self.new_roll()
            self.go("roll")
        elif s == "roll":
            if label == "KEEP":
                self.go("class")
            else:
                self.new_roll()
        elif s == "class":
            self.pick["class"] = label
            self.go("align")
        elif s == "align":
            self.pick["alignment"] = label
            self.typed = ""
            self.go("name")
        elif s == "name":
            if self.typed:
                self.pick["name"] = self.typed
                self.go("sheet")
        elif s == "sheet":
            self.go("disk3" if self.created else "portrait")
        elif s == "portrait" and label == "KEEP":
            self.go("icon")
        elif s == "icon" and label == "EXIT":
            self.go("diskprompt")
        elif s == "add":
            if label == "EXIT":
                self.go("party")
            else:
                self.added.append(label)
                if self.add_closes and len(self.added) == len(self.created):
                    self.go("party")
        elif s == "save_yn":
            if label == "YES":
                self.saving_polls = 2
                self.go("saving")

    def back(self):
        s = self.state
        if s == "align":
            self.go("class")
        elif s == "class":
            self.new_roll()
            self.go("roll")
        elif s == "roll":
            self.go("gender")
        elif s == "gender":
            self.go("race")

    def write(self):
        self.created.append({**self.pick, "roll": dict(self.roll)})
        self.go("race")

    def tick(self):
        """One read of the screen: the write to the disk runs on."""
        if self.state == "saving" and self.stall != "saving":
            self.saving_polls -= 1
            if self.saving_polls <= 0:
                self.saved = True
                self.go("party")
                self.cursor = 6

    def flush(self):
        """The drive shows its directory only once the head has moved."""
        records = []
        for c in self.created:
            sp = spec(c["name"], c["race"], c["gender"], c["class"],
                      c["alignment"])
            records.append(record(sp, c["roll"]))
        disk(records, party=self.saved).save(self.save_disk)


class FakeSession(S.Session):
    """A `Session` whose screen and keyboard are the scripted game."""

    def __init__(self, game):
        self.script = game
        self.kbd = FakeKeyboard(game)
        self.here = str(game.tmp)
        self.save_disk = game.save_disk
        self.attached = "SIDE1.D64"
        self.attaches: list[str] = []
        self.kernal: list[int] = []
        self.world_timeouts: list[float] = []
        self.camp_saves = 0

    def screen(self):
        self.script.tick()
        if self.script.state == "world":
            return None
        return self.script.render()

    def attach(self, path, unit=8, settle=None):
        self.attaches.append(pathlib.Path(path).name)
        if pathlib.Path(path) == pathlib.Path(self.script.save_disk):
            self.script.flush()

    def handle_prompt(self, s=None):
        want = self.wanted_disk(s if s is not None else self.screen())
        if want is None:
            return False
        self.attach(want)
        self.kbd.key("space")
        return True

    def press_kernal(self, code):
        self.kernal.append(code)
        if code == 0x5F:
            self.script.back()

    def wait_for_world(self, timeout=240.0, interval=0.35):
        self.world_timeouts.append(timeout)
        return True

    def save_game(self, to=None):
        self.camp_saves += 1
        self.script.flush()
        return True


class Clock:
    def __init__(self):
        self.now = 0.0

    def __call__(self):
        return self.now

    def sleep(self, seconds):
        self.now += seconds


def drive(tmp, specs, game=None, **kw):
    game = game or FakeGame(tmp)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp / "run"
    code = creation.run(sess, out, specs=specs, clock=clock,
                        sleep=clock.sleep, **kw)
    return code, sess, game, out, json.loads((out / "summary.json").read_text())


PAIR = [spec("VICEFTR", "HUMAN", "MALE", "FIGHTER", "LAWFUL GOOD"),
        spec("VICEDWF", "DWARF", "FEMALE", "FIGHTER/THIEF", "LAWFUL NEUTRAL")]


# -- the driver ------------------------------------------------------------------


def test_every_spec_entry_is_selected_by_its_label(tmp_path):
    """Each character's race, gender, class and alignment are taken by name
    off their own lists, the roll is kept by moving to KEEP rather than by
    pressing Return on the screen's first row, and the records read back match.
    """
    code, sess, game, out, summary = drive(tmp_path, PAIR)
    assert summary["lost"] is None and summary["completed"] is True and code == 0
    picked = [(s, lab) for s, lab in game.chosen if s not in ("party", "name")]
    assert picked[:6] == [("race", "HUMAN"), ("gender", "MALE"),
                          ("roll", "KEEP"), ("class", "FIGHTER"),
                          ("align", "LAWFUL GOOD"), ("sheet", "YES")]
    assert ("race", "DWARF") in picked and ("gender", "FEMALE") in picked
    assert ("class", "FIGHTER/THIEF") in picked
    assert ("align", "LAWFUL NEUTRAL") in picked
    assert ("roll", "ROLL AGAIN") not in picked
    assert (out / "records.txt").read_text().splitlines()[-1] \
        == "all records match the spec"
    assert {p.name for p in out.glob("*.D64")} >= {"rolled.D64", "party.D64"}
    assert list((out / "shots").glob("*.txt"))
    lines = [json.loads(ln) for ln in (out / "run.jsonl").read_text().splitlines()]
    assert [ln["strength"] for ln in lines if ln["kind"] == "roll"] == [17, 12]


def test_the_save_disk_is_reattached_before_each_copy(tmp_path):
    """The drive shows its directory only after the head moves, so a copy
    taken without a re-attach holds no characters: both disks must name them."""
    code, sess, game, out, summary = drive(tmp_path, PAIR)
    assert code == 0
    assert sess.attaches.count("SIDE0.D64") >= 2
    exports = D64.open(str(out / "rolled.D64"))
    for name in (b"\x01VICEFTR", b"\x01VICEDWF"):
        assert len(exports.read_file(name)) == 582


def test_a_label_missing_from_its_list_stops_with_no_key_pressed(tmp_path):
    """No magic-user in a dwarf's class list: the run stops on that screen and
    sends neither an arrow nor Return there."""
    dwarf = spec("VICEMAG", "DWARF", "MALE", "MAGIC-USER", "LAWFUL GOOD")
    code, sess, game, out, summary = drive(tmp_path, [dwarf])
    assert code == 1 and "MAGIC-USER is not in the class list" in summary["lost"]
    assert game.state == "class"
    assert [k for state, k in sess.kbd.sent if state == "class"] == []
    assert list((out / "shots").glob("*lost-label.txt"))


def test_a_label_that_would_select_the_row_above_it_stops(tmp_path):
    """`select_row` goes to the first row containing the label, and
    FIGHTER/MAGIC-USER/THIEF comes before MAGIC-USER/THIEF in an elf's list."""
    elf = spec("VICEELF", "ELF", "MALE", "MAGIC-USER/THIEF", "LAWFUL NEUTRAL")
    code, sess, game, out, summary = drive(tmp_path, [elf])
    assert code == 1 and "would select FIGHTER/MAGIC-USER/THIEF" in summary["lost"]
    assert [k for state, k in sess.kbd.sent if state == "class"] == []


def test_an_unrecognised_screen_stops_with_a_capture_and_no_key(tmp_path, monkeypatch):
    monkeypatch.setattr(creation, "UNRECOGNISED_SECONDS", 5.0)
    game = FakeGame(tmp_path, start="junk")
    code, sess, game, out, summary = drive(tmp_path, PAIR, game)
    assert code == 1 and "an unrecognised screen" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == []
    shot = next((out / "shots").glob("*lost-unrecognised.txt"))
    assert "A SCREEN NOBODY DRAWS" in shot.read_text()


def test_the_add_list_gets_exit_only_while_it_is_still_up(tmp_path):
    """The list stays up after the last add on the C64, so EXIT leaves it; a
    list that had closed itself is not pressed at."""
    code, _sess, game, _out, _s = drive(tmp_path, PAIR)
    assert code == 0
    assert [lab for st, lab in game.chosen if st == "add"] \
        == ["VICEFTR", "VICEDWF", "EXIT"]

    code, _sess, closing, _out, _s = drive(
        tmp_path / "closing", PAIR,
        FakeGame(_mkdir(tmp_path / "closing"), add_closes=True))
    assert code == 0
    assert [lab for st, lab in closing.chosen if st == "add"] \
        == ["VICEFTR", "VICEDWF"]
    assert ("party", "EXIT") not in closing.chosen


def _mkdir(p):
    p.mkdir()
    return p


def test_a_deadline_passing_mid_step_writes_lost_to_the_summary(tmp_path):
    """The write never finishes: the run stops at its own deadline, keeps the
    screen it was looking at, and says so in `summary.json`."""
    game = FakeGame(tmp_path, stall="saving")
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR[:1], max_seconds=200.0,
                        clock=clock, sleep=clock.sleep)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and summary["completed"] is False
    assert "seconds were spent" in summary["lost"]
    assert clock.now < 200.0     # ended inside the cleanup window, not past it
    assert list((out / "shots").glob("*lost-deadline.txt"))


def test_enter_world_waits_with_its_own_budget_and_saves_the_camp(tmp_path):
    code, sess, game, out, summary = drive(tmp_path, PAIR, enter_world=True,
                                           world_budget=450.0)
    assert code == 0
    assert sess.world_timeouts == [450.0] and sess.camp_saves == 1
    assert ("party", "BEGIN ADVENTURING") in game.chosen
    assert (out / "intown.D64").is_file()


def test_the_summary_carries_the_evidence_keys(tmp_path):
    _code, _sess, _game, out, summary = drive(
        tmp_path, PAIR, git={"sha": "abc", "dirty": []}, argv=["--build", "x"])
    assert {"sha", "dirty", "argv", "completed", "lost"} <= set(summary)
    assert summary["argv"] == ["--build", "x"]


# -- check_records ------------------------------------------------------------------


def checked(tmp_path, mutate=None, exceptional=0):
    sp = PAIR[0]
    rec = record(sp, ROLLS[0], exceptional)
    if mutate:
        mutate(rec)
    write_disks(tmp_path, [rec], names=[sp.name])
    return creation.check_records(tmp_path / "rolled.D64",
                                  tmp_path / "party.D64", [sp],
                                  {"VICEFTR": ROLLS[0]})


def test_matching_records_pass(tmp_path):
    assert checked(tmp_path)[-1] == "all records match the spec"


@pytest.mark.parametrize("field, value, word", [
    ("race", 2, "race"),
    ("class_bits", 1, "class_bits"),
    ("name", "VICEFTX", "name"),
    ("strength", 16, "strength"),
])
def test_a_wrong_field_is_rejected(tmp_path, field, value, word):
    lines = checked(tmp_path, lambda r: r.set(field, value))
    assert lines[-1] == "SPEC MISMATCH"
    assert any("MISMATCH" in ln and word in ln for ln in lines[:-1])


def test_exceptional_strength_is_not_compared(tmp_path):
    """The roll screen never shows it: it is rolled after the alignment."""
    assert checked(tmp_path, exceptional=99)[-1] == "all records match the spec"


def test_a_missing_export_is_a_mismatch(tmp_path):
    sp = PAIR[0]
    write_disks(tmp_path, [])
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", [sp],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "MISSING" in lines[0]


@pytest.mark.parametrize("bad", [
    {"name": "TOO LONG A NAME FOR IT", "race": "HUMAN", "gender": "MALE",
     "class": "FIGHTER", "alignment": "LAWFUL GOOD"},
    {"name": "VICE", "race": "ORC", "gender": "MALE", "class": "FIGHTER",
     "alignment": "LAWFUL GOOD"},
    {"name": "VICE", "race": "HUMAN", "gender": "MALE", "class": "PALADIN",
     "alignment": "LAWFUL GOOD"},
])
def test_a_spec_the_screens_cannot_take_is_refused(bad):
    with pytest.raises(ValueError):
        creation.Spec.from_json(bad)


def test_lists_writes_every_races_classes_and_each_classs_alignments(tmp_path):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, lists=True, clock=clock, sleep=clock.sleep)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 0, summary["lost"]
    lists = json.loads((out / "lists.json").read_text())
    assert lists["classes"]["ELF"] == CLASSES["ELF"]
    assert "LAWFUL GOOD" not in lists["alignments"]["THIEF"]
    assert len(lists["alignments"]["FIGHTER"]) == 9
    assert "MAGIC-USER/THIEF" in lists["skipped"]
    assert game.state == "party"
