"""`tools/c64/creation.py` against a scripted game: no emulator, no display.

The fake is a small state machine of the creation screens of C64 Pool of
Radiance -- the roll before the class, the ADD list that stays up, the drive
that only shows its directory after a re-attach -- and the driver under test is
the real one, calling the real `Session.select_row` and `Session.select_bar`
against it.  Its `disk3` screen is a guess, not a measured one.  Records are generated by
`tools/suite/testparty.py`, never read from game data.
"""

import json
import pathlib

import pytest
from conftest import load_tools_module

from automap.screen import _SCREEN_TO_ASCII, SCREEN_COLS, SCREEN_ROWS, Screen
from goldbox import c64_port, savegame
from goldbox.d64 import D64

creation = load_tools_module("creation")
testparty = load_tools_module("testparty")
S = creation.S

GAME = c64_port.by_key("pool-of-radiance")

CLASSES = {
    "DWARF": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "ELF": ["FIGHTER", "MAGIC-USER", "THIEF", "FIGHTER/MAGIC-USER",
            "FIGHTER/THIEF", "FIGHTER/MAGIC-USER/THIEF", "MAGIC-USER/THIEF"],
    "GNOME": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "HALF-ELF": ["CLERIC", "FIGHTER", "MAGIC-USER", "THIEF", "CLERIC/FIGHTER",
                 "CLERIC/FIGHTER/MAGIC-USER", "CLERIC/MAGIC-USER",
                 "FIGHTER/MAGIC-USER", "FIGHTER/THIEF",
                 "FIGHTER/MAGIC-USER/THIEF", "MAGIC-USER/THIEF"],
    "HALFLING": ["FIGHTER", "THIEF", "FIGHTER/THIEF"],
    "HUMAN": ["CLERIC", "FIGHTER", "MAGIC-USER", "THIEF"],
}
ROLLS = [
    dict(strength=17, intelligence=16, wisdom=15, dexterity=14,
         constitution=16, charisma=13),
    dict(strength=12, intelligence=15, wisdom=10, dexterity=13,
         constitution=11, charisma=9),
    dict(strength=10, intelligence=11, wisdom=12, dexterity=15,
         constitution=14, charisma=8),
]


def spec(name="VICEFTR", race="HUMAN", gender="MALE", cls="FIGHTER",
         alignment="LAWFUL GOOD"):
    return creation.Spec.from_json({"name": name, "race": race,
                                    "gender": gender, "class": cls,
                                    "alignment": alignment})


def record(sp, roll, exceptional=0):
    """What the engine would have written for SP, generated by `testparty`."""
    one = testparty.build(testparty.Spec(
        name=sp.name, race=creation.RACES[sp.race],
        sex=creation.GENDERS[sp.gender], levels=dict(sp.classes),
        abilities=dict(roll), alignment=creation.ALIGNMENTS.index(sp.alignment),
        age=20, experience=0, portrait=(0, 1)))
    if exceptional:
        one.record.set("exceptional_strength", exceptional)
    return one.record


def disk(records, party=False, exports=True, names=None, camp=False):
    """A save disk: the `\\x01NAME` exports, and SAVEDGAME0 once saved.
    `names` are the file names when they differ from the records' own; `camp`
    makes the SAVEDGAME0 differ from a party-menu save's."""
    image = D64.blank()
    if exports:
        for rec, name in zip(records, names or [r.name for r in records]):
            image.write_file(b"\x01" + name.encode(), rec.to_prg())
    if party:
        sg0 = savegame.SaveGame0(bytes(GAME.save_size), GAME)
        for i, rec in enumerate(records):
            sg0.write_record(i, rec)
        prg = bytearray(sg0.to_prg())
        if camp:
            prg[-1] ^= 1
        image.write_file(b"SAVEDGAME0", bytes(prg))
    return image


def write_disks(tmp, records, names=None):
    """The two disks a build leaves: exports before the add, slots after."""
    disk(records, names=names).save(str(tmp / "rolled.D64"))
    disk(records, party=True, exports=False).save(str(tmp / "party.D64"))


# -- the scripted game ---------------------------------------------------------


COLS = 40


def encode(ch):
    if ch == "@":
        return 0
    if "A" <= ch <= "Z":
        return ord(ch) - 64
    if ch in "[£]^_":
        return 27 + "[£]^_".index(ch)
    return ord(ch)


class FakeKeyboard:
    def __init__(self, game):
        self.game, self.sent = game, []

    def key(self, name, hold=0.0, gap=0.0):
        self.sent.append((self.game.state, name))
        self.game.key(name)

    def text(self, s, hold=0.0, gap=0.0):
        self.sent.append((self.game.state, "text " + s))
        self.game.typed += s.upper()

    def screenshot(self, path, **_kw):
        pathlib.Path(path).write_bytes(b"png")
        return True


class FakeGame:
    """The screens of CREATE NEW CHARACTER, ADD and SAVE, one state each."""

    PARTY_EMPTY = ["CREATE NEW CHARACTER", "ADD CHARACTER TO PARTY",
                   "LOAD SAVED GAME"]
    PARTY_FULL = ["CREATE NEW CHARACTER", "DROP CHARACTER", "MODIFY CHARACTER",
                  "VIEW CHARACTER", "ADD CHARACTER TO PARTY",
                  "REMOVE CHARACTER FROM PARTY", "SAVE CURRENT GAME",
                  "BEGIN ADVENTURING"]

    def __init__(self, tmp, rolls=ROLLS, add_closes=False, stall=None,
                 start="party", lose_first=None, slow=None, trim=(),
                 roster=(), tail=None, slow_roll=False):
        """`stall`: a state whose keys do nothing.  `lose_first`: a state whose
        first Return is dropped.  `slow`: state -> (polls, redraws), a Return
        that is accepted but takes that many screen reads to show its result,
        the screen redrawn meanwhile or left as it was.  `trim`: class labels
        the roll does not qualify for, left off the class list.  `roster`:
        names already on the ADD list that no spec asked for.  `tail`:
        `(state, column, text)` drawn on that screen's first row."""
        self.roster, self.tail = tuple(roster), tail
        self.slow_roll, self.roll_reads = slow_roll, 0
        self.trim = tuple(trim)
        self.tmp, self.rolls = tmp, list(rolls)
        self.add_closes, self.stall = add_closes, stall
        self.lose_first, self.slow = lose_first, dict(slow or {})
        self.delayed = None             # [polls left, state the key was sent in]
        self.camped = False
        self.state, self.cursor, self.typed = start, 0, ""
        self.rolled = 0
        self.roll = {}
        self.pick = {}
        self.created: list = []      # (spec-ish dict, roll) in memory
        self.added: list[str] = []
        self.on_disk_created: list = []
        self.saved = False
        self.saving_polls = 0
        self.chosen: list[tuple[str, str]] = []
        self.save_disk = str(tmp / "SIDE0.D64")
        D64.blank().save(self.save_disk)

    # -- what is on each screen ---------------------------------------------

    def items(self):
        s = self.state
        if s == "party":
            return self.PARTY_FULL if self.added else self.PARTY_EMPTY
        if s == "race":
            return list(creation.RACES) + ["EXIT"]
        if s == "gender":
            return list(creation.GENDERS)
        if s == "roll":
            return ["ROLL AGAIN", "KEEP"]
        if s == "class":
            return [c for c in CLASSES[self.pick["race"]] if c not in self.trim]
        if s == "align":
            aligns = list(creation.ALIGNMENTS)
            if "CLERIC" in self.pick["class"]:
                aligns.remove("TRUE NEUTRAL")
            if "THIEF" in self.pick["class"]:
                aligns = [a for a in aligns
                          if a not in ("LAWFUL GOOD", "CHAOTIC GOOD")]
            return aligns
        if s == "sheet":
            return ["YES", "NO"]
        if s == "add":
            return list(self.roster) + [c["name"] for c in self.created] + ["EXIT"]
        return []

    def render(self):
        codes = bytearray(0x20 for _ in range(25 * COLS))
        colours = bytearray(5 for _ in range(25 * COLS))

        def put(row, col, text, hot=False):
            for i, ch in enumerate(text):
                codes[row * COLS + col + i] = encode(ch)
                if hot:
                    colours[row * COLS + col + i] = 1

        s, items = self.state, self.items()

        def listing(prompt, col, first=2, whole_row=False):
            for i, label in enumerate(items):
                hot = i == self.cursor
                put(first + i, col, label, hot)
                if hot and whole_row:
                    for c in range(1, 39):
                        colours[(first + i) * COLS + c] = 1
            put(first + len(items) + 1, 2, prompt)

        if s == "party":
            for i, label in enumerate(items):
                put(13 + i, 2, label, i == self.cursor)
        elif s == "race":
            listing("PICK RACE", 2)
        elif s == "gender":
            listing("PICK GENDER", 2)
        elif s == "roll":
            put(2, 1, f"RACE {self.pick['race']}")
            put(3, 1, f"GENDER {self.pick['gender']}")
            drawn = list(self.roll.items())
            if self.slow_roll and self.rolled > 1 and self.roll_reads < 4:
                drawn = drawn[:3]     # a redraw under way: three lines so far
            for i, (k, v) in enumerate(drawn):
                put(5 + i, 1, f"{k.upper():<14}{v}")
            for i, label in enumerate(items):
                put(12 + i, 2, label, i == self.cursor)
        elif s == "class":
            listing("PICK CLASS", 1, whole_row=True)
        elif s == "align":
            listing("PICK ALIGNMENT", 2)
        elif s == "name":
            put(2, 2, "INPUT NAME OF CHARACTER")
            put(3, 2, self.typed.lower().upper())
        elif s == "sheet":
            put(13, 28, "SAVE?")
            for i, label in enumerate(items):
                put(15 + i, 28, label, i == self.cursor)
        elif s == "disk3":
            # Unmeasured: this prompt after a second character's sheet is a
            # guess from the loader's code.
            put(18, 2, "INSERT GAME DISK #3")
            put(24, 0, "PRESS ANY KEY TO CONTINUE")
        elif s in ("portrait", "icon", "save_yn"):
            bar = {"portrait": ["CHANGE:HEAD", "BODY", "KEEP"],
                   "icon": ["ICON:PARTS", "COLOR", "SIZE", "EXIT"],
                   "save_yn": ["SAVE GAME: YES", "NO"]}[s]
            col = 0
            for i, word in enumerate(bar):
                label = word.split(":")[-1].split(" ")[-1]
                put(24, col, word + " ")
                start = col + len(word) - len(label)
                if i == self.cursor:
                    put(24, start, label, True)
                col += len(word) + 1
        elif s == "diskprompt":
            put(24, 0, "INSERT YOUR SAVE GAME DISK")
        elif s == "add":
            for i, label in enumerate(items):
                star = "*" if label in self.added else " "
                put(2 + i, 3, star)
                put(2 + i, 4, label, i == self.cursor)
            put(2 + len(items) + 2, 2, "ADD CHARACTER TO PARTY")
        elif s == "saving":
            put(10, 2, "SAVING GAME")
            for i, label in enumerate(self.PARTY_FULL):
                put(13 + i, 2, label)
        elif s == "junk":
            put(5, 5, "A SCREEN NOBODY DRAWS")
        if self.tail and self.tail[0] == s:
            put(2, self.tail[1], self.tail[2])
        if self.delayed and self.slow[self.delayed[1]][1]:
            put(22, 5, "LOADING")     # the screen changes, not to the next one
        # The game's window frame is on every screen it draws: a `$` in the
        # first and last column of rows 1 to 22 and a `@[[[` rule above and
        # below.  A reader that starts at column 0 must cope with it.
        for r in range(1, 23):
            put(r, 0, "$")
            put(r, COLS - 1, "$")
        for r in (0, 23):
            put(r, 0, "@" + "[" * (COLS - 2) + "@")
        return Screen(bytes(codes), bytes(colours), 0x0400)

    def bar_words(self):
        return {"portrait": ["HEAD", "BODY", "KEEP"],
                "icon": ["PARTS", "COLOR", "SIZE", "EXIT"],
                "save_yn": ["YES", "NO"]}[self.state]

    # -- what a key does ----------------------------------------------------

    def new_roll(self):
        self.roll_reads = 0
        self.roll = dict(self.rolls[self.rolled % len(self.rolls)])
        self.rolled += 1

    def go(self, state):
        self.state, self.cursor = state, 0

    def key(self, name):
        if self.stall == self.state or self.delayed:
            return
        if name == "Return" and self.lose_first == self.state:
            self.lose_first = None
            return
        if name == "Return" and self.state in self.slow:
            self.delayed = [self.slow[self.state][0], self.state]
            return
        s = self.state
        if name in ("Down", "Right"):
            n = len(self.bar_words() if s in ("portrait", "icon", "save_yn")
                    else self.items())
            self.cursor = min(self.cursor + 1, n - 1)
        elif name in ("Up", "Left"):
            self.cursor = max(self.cursor - 1, 0)
        elif name == "space":
            if s == "diskprompt":
                self.write()
            elif s == "disk3":
                self.go("portrait")
        elif name == "Return":
            self.enter()

    def enter(self):
        s = self.state
        words = (self.bar_words() if s in ("portrait", "icon", "save_yn")
                 else self.items())
        label = words[self.cursor] if words else ""
        self.chosen.append((s, label))
        if s == "party":
            self.go({"CREATE NEW CHARACTER": "race",
                     "ADD CHARACTER TO PARTY": "add",
                     "SAVE CURRENT GAME": "save_yn",
                     "BEGIN ADVENTURING": "world"}[label])
        elif s == "race":
            if label == "EXIT":
                self.go("party")
            else:
                self.pick["race"] = label
                self.go("gender")
        elif s == "gender":
            self.pick["gender"] = label
            self.new_roll()
            self.go("roll")
        elif s == "roll":
            if label == "KEEP":
                self.go("class")
            else:
                self.new_roll()
        elif s == "class":
            self.pick["class"] = label
            self.go("align")
        elif s == "align":
            self.pick["alignment"] = label
            self.typed = ""
            self.go("name")
        elif s == "name":
            if self.typed:
                self.pick["name"] = self.typed
                self.go("sheet")
        elif s == "sheet":
            self.go("disk3" if self.created else "portrait")
        elif s == "portrait" and label == "KEEP":
            self.go("icon")
        elif s == "icon" and label == "EXIT":
            self.go("diskprompt")
        elif s == "add":
            if label == "EXIT":
                self.go("party")
            else:
                self.added.append(label)
                if self.add_closes and len(self.added) == len(self.created):
                    self.go("party")
        elif s == "save_yn":
            if label == "YES":
                self.saving_polls = 2
                self.go("saving")

    def back(self):
        s = self.state
        if s == "align":
            self.go("class")
        elif s == "class":
            self.new_roll()
            self.go("roll")
        elif s == "roll":
            self.go("gender")
        elif s == "gender":
            self.go("race")

    def write(self):
        self.created.append({**self.pick, "roll": dict(self.roll)})
        self.go("race")

    def tick(self):
        """One read of the screen: the write to the disk runs on."""
        if self.delayed:
            self.delayed[0] -= 1
            if self.delayed[0] <= 0:
                self.delayed = None
                self.enter()
        if self.state == "roll":
            self.roll_reads += 1
        if self.state == "saving" and self.stall != "saving":
            self.saving_polls -= 1
            if self.saving_polls <= 0:
                self.saved = True
                self.go("party")
                self.cursor = 6

    def flush(self):
        """The drive shows its directory only once the head has moved."""
        records = []
        for c in self.created:
            sp = spec(c["name"], c["race"], c["gender"], c["class"],
                      c["alignment"])
            records.append(record(sp, c["roll"]))
        disk(records, party=self.saved, camp=self.camped).save(self.save_disk)


class FakeSession(S.Session):
    """A `Session` whose screen and keyboard are the scripted game."""

    def __init__(self, game):
        self.script = game
        self.kbd = FakeKeyboard(game)
        self.here = str(game.tmp)
        self.save_disk = game.save_disk
        self.attached = "SIDE1.D64"
        self.attaches: list[str] = []
        self.kernal: list[int] = []
        self.world_timeouts: list[float] = []
        self.camp_saves = 0
        self.camp_lands = True
        self.camp_wipes = False
        self.world_arrives = True

    def screen(self):
        self.script.tick()
        if self.script.state == "world":
            return None
        return self.script.render()

    def attach(self, path, unit=8, settle=None):
        self.attaches.append(pathlib.Path(path).name)
        if pathlib.Path(path) == pathlib.Path(self.script.save_disk):
            self.script.flush()

    def handle_prompt(self, s=None):
        want = self.wanted_disk(s if s is not None else self.screen())
        if want is None:
            return False
        self.attach(want)
        self.kbd.key("space")
        return True

    def press_kernal(self, code):
        self.kernal.append(code)
        if code == 0x5F:
            self.script.back()

    def wait_for_world(self, timeout=240.0, interval=0.35):
        self.world_timeouts.append(timeout)
        return self.world_arrives

    def save_game(self, to=None):
        self.camp_saves += 1
        self.script.camped = self.camp_lands
        self.script.flush()
        if self.camp_wipes:
            D64.blank().save(self.script.save_disk)
        return True


class Clock:
    def __init__(self):
        self.now = 0.0

    def __call__(self):
        return self.now

    def sleep(self, seconds):
        self.now += seconds


def drive(tmp, specs, game=None, **kw):
    game = game or FakeGame(tmp)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp / "run"
    code = creation.run(sess, out, specs=specs, clock=clock,
                        sleep=clock.sleep, **kw)
    return code, sess, game, out, json.loads((out / "summary.json").read_text())


PAIR = [spec("VICEFTR", "HUMAN", "MALE", "FIGHTER", "LAWFUL GOOD"),
        spec("VICEDWF", "DWARF", "FEMALE", "FIGHTER/THIEF", "LAWFUL NEUTRAL")]


# -- the driver ------------------------------------------------------------------


def test_every_spec_entry_is_selected_by_its_label(tmp_path):
    """Each character's race, gender, class and alignment are taken by name
    off their own lists, the roll is kept by moving to KEEP rather than by
    pressing Return on the screen's first row, and the records read back match.
    """
    code, sess, game, out, summary = drive(tmp_path, PAIR)
    assert summary["lost"] is None and summary["completed"] is True and code == 0
    picked = [(s, lab) for s, lab in game.chosen if s not in ("party", "name")]
    assert picked[:6] == [("race", "HUMAN"), ("gender", "MALE"),
                          ("roll", "KEEP"), ("class", "FIGHTER"),
                          ("align", "LAWFUL GOOD"), ("sheet", "YES")]
    assert ("race", "DWARF") in picked and ("gender", "FEMALE") in picked
    assert ("class", "FIGHTER/THIEF") in picked
    assert ("align", "LAWFUL NEUTRAL") in picked
    assert ("roll", "ROLL AGAIN") not in picked
    assert (out / "records.txt").read_text().splitlines()[-1] \
        == "all records match the spec"
    assert {p.name for p in out.glob("*.D64")} >= {"rolled.D64", "party.D64"}
    assert list((out / "shots").glob("*.txt"))
    lines = [json.loads(ln) for ln in (out / "run.jsonl").read_text().splitlines()]
    assert [ln["strength"] for ln in lines if ln["kind"] == "roll"] == [17, 12]


def test_the_save_disk_is_reattached_before_each_copy(tmp_path):
    """The drive shows its directory only after the head moves, so a copy
    taken without a re-attach holds no characters: both disks must name them."""
    code, sess, game, out, summary = drive(tmp_path, PAIR)
    assert code == 0
    assert sess.attaches.count("SIDE0.D64") >= 2
    exports = D64.open(str(out / "rolled.D64"))
    for name in (b"\x01VICEFTR", b"\x01VICEDWF"):
        assert len(exports.read_file(name)) == 582


def test_a_class_the_race_is_never_offered_is_refused_before_any_key(tmp_path):
    """No magic-user in a dwarf's class list: the refusal comes before the
    first character is created, even when the dwarf is the second spec."""
    dwarf = spec("VICEMAG", "DWARF", "MALE", "MAGIC-USER", "LAWFUL GOOD")
    code, sess, game, out, summary = drive(tmp_path, [PAIR[0], dwarf])
    assert code == 1 and "a DWARF is never offered MAGIC-USER" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == [] and sess.attaches == []


@pytest.mark.parametrize("cls, alignment", [
    ("THIEF", "LAWFUL GOOD"), ("THIEF", "CHAOTIC GOOD"),
    ("FIGHTER/THIEF", "LAWFUL GOOD"), ("CLERIC", "TRUE NEUTRAL"),
    ("CLERIC/FIGHTER", "TRUE NEUTRAL")])
def test_an_alignment_the_class_is_never_offered_is_refused_before_any_key(
        tmp_path, cls, alignment):
    bad = spec("VICEBAD", "HALF-ELF", "MALE", cls, alignment)
    code, sess, game, out, summary = drive(tmp_path, [PAIR[0], bad])
    assert code == 1 and f"{cls} is never offered {alignment}" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == [] and sess.attaches == []


def test_the_alignment_table_is_the_lists_the_screens_draw(tmp_path):
    """Every class a list offers, opened on the fake, against the table."""
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    assert creation.run(sess, out, lists=True, clock=clock,
                        sleep=clock.sleep) == 0
    found = json.loads((out / "lists.json").read_text())["alignments"]
    assert "CLERIC" in found and "FIGHTER/THIEF" in found
    assert {c: tuple(a) for c, a in found.items()} \
        == {c: creation.alignments_offered(c) for c in found}


def test_a_roll_that_trims_the_class_list_stops_on_that_screen(tmp_path):
    """The roll, not the race, drops THIEF: only the screen can say so, and the
    run stops there sending neither an arrow nor Return."""
    game = FakeGame(tmp_path, trim=("THIEF",))
    thief = spec("VICETHI", "HUMAN", "MALE", "THIEF", "LAWFUL NEUTRAL")
    code, sess, game, out, summary = drive(tmp_path, [thief], game)
    assert code == 1 and "THIEF is not in the class list" in summary["lost"]
    assert game.state == "class"
    assert [k for state, k in sess.kbd.sent if state == "class"] == []
    assert list((out / "shots").glob("*lost-label.txt"))


SHADOWED = [("ELF", "MAGIC-USER/THIEF", "FIGHTER/MAGIC-USER/THIEF"),
            ("HALF-ELF", "MAGIC-USER/THIEF", "FIGHTER/MAGIC-USER/THIEF"),
            ("HALF-ELF", "FIGHTER/MAGIC-USER", "CLERIC/FIGHTER/MAGIC-USER")]


@pytest.mark.parametrize("race, cls, earlier", SHADOWED)
def test_a_class_that_is_the_tail_of_a_longer_row_is_accepted_and_selected(
        tmp_path, race, cls, earlier):
    """The class rows are bare labels and are matched whole, so the class is not
    mistaken for the longer row above it."""
    want = spec("VICEEXA", race, "MALE", cls, "LAWFUL NEUTRAL")
    creation.check_specs([want])
    code, sess, game, out, summary = drive(tmp_path, [want])
    assert code == 0 and summary["lost"] is None
    assert ("class", cls) in game.chosen
    assert ("class", earlier) not in game.chosen


def test_a_roster_row_containing_the_name_is_refused_before_return(tmp_path):
    """The ADD list is matched by containment, so a leftover VICEFTR above the
    spec's VICE would be taken for it."""
    game = FakeGame(tmp_path, roster=("VICEFTR",))
    code, sess, game, out, summary = drive(
        tmp_path, [spec("VICE")], game)
    assert code == 1 and "VICE would select VICEFTR" in summary["lost"]
    assert [k for st, k in sess.kbd.sent if st == "add"] == []


def test_an_exact_label_present_only_as_a_non_bare_row_is_refused(tmp_path):
    """The label sits in the 26-column slice `entries` reads, but the row also
    holds text further right, so the whole-row match could never succeed."""
    game = FakeGame(tmp_path, tail=("class", 30, "X"))
    code, sess, game, out, summary = drive(
        tmp_path, [spec("VICECLE", cls="CLERIC")], game)
    assert code == 1 and "no whole row of the class list is CLERIC" \
        in summary["lost"]
    assert [k for st, k in sess.kbd.sent if st == "class"] == []


RECORDED_RACE_LIST = [
    "@" + "[" * 38 + "@",
    "$" + " " * 38 + "$",
    "$ DWARF".ljust(39) + "$",
    "$ ELF".ljust(39) + "$",
    "$ GNOME".ljust(39) + "$",
    "$ HALF-ELF".ljust(39) + "$",
    "$ HALFLING".ljust(39) + "$",
    "$ HUMAN".ljust(39) + "$",
    "$ EXIT".ljust(39) + "$",
    "$" + " " * 38 + "$",
    "$" + " " * 38 + "$",
    "$PICK RACE".ljust(39) + "$",
]


def test_a_label_inside_the_windows_frame_is_a_whole_row():
    """The race list as the game drew it (a recorded boot's screen): the
    frame glyph in the first and last column is not text of the row."""
    codes = bytearray(0x20 for _ in range(25 * COLS))
    for r, line in enumerate(RECORDED_RACE_LIST):
        for i, ch in enumerate(line):
            codes[r * COLS + i] = encode(ch)
    s = Screen(bytes(codes), bytes(5 for _ in codes), 0xCC00)
    assert S.Session._exact_hit(s, "HUMAN") == (7, 2)
    assert S.Session._exact_hit(s, "HUM") is None


def test_the_class_table_is_the_lists_the_screens_draw():
    assert {r: list(c) for r, c in creation.CLASSES_BY_RACE.items()} == CLASSES


@pytest.mark.parametrize("specs, why", [
    ([], "names no characters"),
    ([PAIR[0], PAIR[0]], "a name is used twice"),
    ([spec("VICE"), spec("VICEFTR")], "part of another name"),
])
def test_a_party_the_driver_cannot_build_is_refused_before_any_key(
        tmp_path, specs, why):
    code, sess, _game, _out, summary = drive(tmp_path, specs)
    assert code == 1 and why in summary["lost"] and sess.kbd.sent == []


def test_an_unrecognised_screen_stops_with_a_capture_and_no_key(tmp_path, monkeypatch):
    monkeypatch.setattr(creation, "UNRECOGNISED_SECONDS", 5.0)
    game = FakeGame(tmp_path, start="junk")
    code, sess, game, out, summary = drive(tmp_path, PAIR, game)
    assert code == 1 and "an unrecognised screen" in summary["lost"]
    assert sess.kbd.sent == [] and sess.kernal == []
    shot = next((out / "shots").glob("*lost-unrecognised.txt"))
    assert "A SCREEN NOBODY DRAWS" in shot.read_text()


def test_the_add_list_gets_exit_only_while_it_is_still_up(tmp_path):
    """The list stays up after the last add on the C64, so EXIT leaves it; a
    list that had closed itself is not pressed at."""
    code, _sess, game, _out, _s = drive(tmp_path, PAIR)
    assert code == 0
    assert [lab for st, lab in game.chosen if st == "add"] \
        == ["VICEFTR", "VICEDWF", "EXIT"]

    code, _sess, closing, _out, _s = drive(
        tmp_path / "closing", PAIR,
        FakeGame(_mkdir(tmp_path / "closing"), add_closes=True))
    assert code == 0
    assert [lab for st, lab in closing.chosen if st == "add"] \
        == ["VICEFTR", "VICEDWF"]
    assert ("party", "EXIT") not in closing.chosen


def _mkdir(p):
    p.mkdir()
    return p


def test_a_deadline_passing_mid_step_writes_lost_to_the_summary(tmp_path):
    """The write never finishes: the run stops at its own deadline, keeps the
    screen it was looking at, and says so in `summary.json`."""
    game = FakeGame(tmp_path, stall="saving")
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR[:1], max_seconds=200.0,
                        clock=clock, sleep=clock.sleep)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and summary["completed"] is False
    assert "seconds were spent" in summary["lost"]
    assert clock.now < 200.0     # ended inside the cleanup window, not past it
    assert list((out / "shots").glob("*lost-deadline.txt"))


def test_enter_world_waits_with_its_own_budget_and_saves_the_camp(tmp_path):
    code, sess, game, out, summary = drive(tmp_path, PAIR, enter_world=True,
                                           world_budget=450.0)
    assert code == 0
    assert sess.world_timeouts == [450.0] and sess.camp_saves == 1
    assert ("party", "BEGIN ADVENTURING") in game.chosen
    assert (out / "intown.D64").is_file()


def test_the_summary_carries_the_evidence_keys(tmp_path):
    _code, _sess, _game, out, summary = drive(
        tmp_path, PAIR, git={"sha": "abc", "dirty": []}, argv=["--build", "x"])
    assert {"sha", "dirty", "argv", "completed", "lost"} <= set(summary)
    assert summary["argv"] == ["--build", "x"]


def test_a_key_that_did_nothing_is_sent_once_more(tmp_path):
    """The first Return on the gender list is lost and the screen does not
    change, so exactly one resend follows."""
    game = FakeGame(tmp_path, lose_first="gender")
    code, sess, _game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert code == 0, summary["lost"]
    assert [k for st, k in sess.kbd.sent if st == "gender"] == ["Return", "Return"]


def test_a_slow_key_is_not_sent_again(tmp_path):
    """A Return that is taken but whose result takes 15 s, the screen redrawn
    meanwhile, is sent once: only a screen identical to the one before the key
    counts as a key that did nothing."""
    game = FakeGame(tmp_path, slow={"gender": (30, True)})
    code, sess, _game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert code == 0, summary["lost"]
    assert [k for st, k in sess.kbd.sent if st == "gender"] == ["Return"]


def test_create_new_character_is_never_sent_twice(tmp_path):
    """Its overlay takes 3.4-12 s to draw with the party menu still showing,
    longer than the resend window, so a resend would land on PICK RACE."""
    game = FakeGame(tmp_path, slow={"party": (30, False)})
    code, sess, _game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert code == 0, summary["lost"]
    first = next(i for i, (st, _k) in enumerate(sess.kbd.sent) if st != "party")
    assert [k for _st, k in sess.kbd.sent[:first]] == ["Return"]


def test_a_camp_save_that_did_not_land_is_lost(tmp_path):
    """`save_game` returns True whether or not the disk changed."""
    sess_game = FakeGame(tmp_path)
    sess = FakeSession(sess_game)
    sess.camp_lands = False
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR, clock=clock, sleep=clock.sleep,
                        enter_world=True)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and "camp save did not land" in summary["lost"]


def test_a_camp_save_that_wrote_no_savegame_is_lost(tmp_path):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    sess.camp_wipes = True
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR, clock=clock, sleep=clock.sleep,
                        enter_world=True)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and "intown.D64 holds no SAVEDGAME0" in summary["lost"]


def test_records_are_checked_before_the_world_is_entered(tmp_path):
    """A world that never arrives still leaves `records.txt`."""
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    sess.world_arrives = False
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, specs=PAIR, clock=clock, sleep=clock.sleep,
                        enter_world=True)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 1 and "world bar did not come" in summary["lost"]
    assert (out / "records.txt").read_text().splitlines()[-1] \
        == "all records match the spec"


@pytest.mark.parametrize("name", ["EYES", "VICEYESX", "EXITER", "NEXIT"])
def test_a_name_holding_a_menu_word_is_refused(name):
    with pytest.raises(ValueError, match="menu"):
        spec(name)


def test_a_stop_before_the_run_still_leaves_a_summary(tmp_path, monkeypatch):
    """Staging raises before `run` is reached; `main` still writes one."""
    class Slot:
        dir = str(tmp_path / "slot")

        def teardown(self):
            pass

        def release(self):
            pass

    out = tmp_path / "evidence"
    monkeypatch.setattr(creation.S, "claim_slot", lambda *a, **k: Slot())

    def boom(*_a, **_k):
        raise RuntimeError("no disks to stage")
    monkeypatch.setattr(creation.S, "stage_disks", boom)
    monkeypatch.setattr(creation.evidence, "default_out", lambda *a, **k: out)
    monkeypatch.setattr(creation.runlog, "catch_signals", lambda: None)
    with pytest.raises(RuntimeError):
        creation.main(["--lists", "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    summary = json.loads((out / "summary.json").read_text())
    assert summary["completed"] is False and "no disks to stage" in summary["lost"]


class Slot:
    def __init__(self, tmp):
        self.dir = str(tmp / "slot")
        self.calls = []

    def teardown(self):
        self.calls.append("teardown")

    def release(self):
        self.calls.append("release")


def stage_main(tmp_path, monkeypatch, slot=None):
    """`main` with the pool, the evidence directory and the signals replaced."""
    out = tmp_path / "evidence"
    monkeypatch.setattr(creation.S, "claim_slot", lambda *a, **k: slot)
    monkeypatch.setattr(creation.evidence, "default_out", lambda *a, **k: out)
    monkeypatch.setattr(creation.runlog, "catch_signals", lambda: None)
    return out


def test_a_refused_spec_leaves_a_summary_and_claims_no_slot(tmp_path, monkeypatch):
    def claim(*_a, **_k):
        raise AssertionError("a slot was claimed for a refused party")
    out = stage_main(tmp_path, monkeypatch)
    monkeypatch.setattr(creation.S, "claim_slot", claim)
    bad = tmp_path / "bad.json"
    bad.write_text(json.dumps([{"name": "VICEMAG", "race": "DWARF",
                                "gender": "MALE", "class": "MAGIC-USER",
                                "alignment": "LAWFUL GOOD"}]))
    with pytest.raises(SystemExit, match="never offered MAGIC-USER"):
        creation.main(["--build", str(bad), "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    summary = json.loads((out / "summary.json").read_text())
    assert summary["completed"] is False
    assert "never offered MAGIC-USER" in summary["lost"]


def test_a_full_pool_leaves_a_summary(tmp_path, monkeypatch):
    out = stage_main(tmp_path, monkeypatch)

    def full(*_a, **_k):
        raise RuntimeError("every slot is leased")
    monkeypatch.setattr(creation.S, "claim_slot", full)
    with pytest.raises(RuntimeError):
        creation.main(["--lists", "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    assert "every slot is leased" in \
        json.loads((out / "summary.json").read_text())["lost"]


def test_a_summary_that_cannot_be_written_still_releases_the_slot(
        tmp_path, monkeypatch):
    slot = Slot(tmp_path)
    stage_main(tmp_path, monkeypatch, slot)
    monkeypatch.setattr(creation.S, "stage_disks",
                        lambda *a, **k: (_ for _ in ()).throw(RuntimeError("x")))

    def cannot(*_a, **_k):
        raise OSError("disk full")
    monkeypatch.setattr(creation, "write_summary", cannot)
    with pytest.raises(OSError):
        creation.main(["--lists", "--issue", "1", "--run", "r",
                       "--disks", str(tmp_path)])
    assert slot.calls == ["teardown", "release"]


def test_a_summary_that_cannot_be_written_still_closes_the_log(tmp_path, monkeypatch):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    closed = []
    real = creation.runlog.Log.close
    monkeypatch.setattr(creation.runlog.Log, "close",
                        lambda self: (closed.append(1), real(self))[1])

    def cannot(*_a, **_k):
        raise OSError("disk full")
    monkeypatch.setattr(creation, "write_summary", cannot)
    clock = Clock()
    with pytest.raises(OSError):
        creation.run(sess, tmp_path / "run", specs=PAIR, clock=clock,
                     sleep=clock.sleep)
    assert closed == [1]


# -- a constitution band -----------------------------------------------------------


def con_roll(con):
    return dict(strength=12, intelligence=11, wisdom=10, dexterity=13,
                constitution=con, charisma=9)


def gnome(band):
    return creation.Spec.from_json({
        "name": "VICEGNO", "race": "GNOME", "gender": "MALE",
        "class": "FIGHTER", "alignment": "LAWFUL GOOD", "constitution": band})


def test_a_roll_outside_the_band_is_rerolled_and_the_first_inside_is_kept(
        tmp_path):
    game = FakeGame(tmp_path, rolls=[con_roll(c) for c in (14, 12, 9, 16)])
    code, _sess, game, out, summary = drive(tmp_path, [gnome([8, 10])], game)
    assert code == 0
    chosen = [label for state, label in game.chosen if state == "roll"]
    assert chosen == ["ROLL AGAIN", "ROLL AGAIN", "KEEP"]
    assert summary["rolls"]["VICEGNO"]["constitution"] == 9
    assert summary["roll_counts"]["VICEGNO"] == {"count": 3, "lowest": 9,
                                                 "highest": 14}
    assert (out / "records.txt").read_text().splitlines()[-1] == \
        "all records match the spec"


def test_a_reroll_still_being_drawn_is_waited_out_not_lost(tmp_path):
    game = FakeGame(tmp_path, rolls=[con_roll(14), con_roll(9)],
                    slow_roll=True)
    code, _sess, game, _out, summary = drive(tmp_path, [gnome([8, 10])], game)
    assert code == 0, summary["lost"]
    assert summary["rolls"]["VICEGNO"]["constitution"] == 9


def test_the_help_says_the_roll_limit_needs_seconds(capsys):
    with pytest.raises(SystemExit):
        creation.main(["--help"])
    text = " ".join(capsys.readouterr().out.split())
    assert "--max-rolls" in text and "larger --max-seconds" in text


def test_a_roll_inside_the_band_stops_at_once(tmp_path):
    game = FakeGame(tmp_path, rolls=[con_roll(9), con_roll(14)])
    _code, _sess, game, _out, summary = drive(tmp_path, [gnome([8, 10])], game)
    assert [label for state, label in game.chosen if state == "roll"] == ["KEEP"]
    assert summary["roll_counts"]["VICEGNO"]["count"] == 1


def test_a_spec_without_a_band_keeps_the_first_roll(tmp_path):
    game = FakeGame(tmp_path, rolls=[con_roll(16), con_roll(9)])
    _code, _sess, game, _out, summary = drive(tmp_path, PAIR[:1], game)
    assert [label for state, label in game.chosen if state == "roll"] == ["KEEP"]


def test_the_same_roll_twice_is_taken_as_it_is_and_rolled_on(tmp_path):
    game = FakeGame(tmp_path, rolls=[con_roll(14), con_roll(14), con_roll(9)])
    code, _sess, game, _out, _summary = drive(tmp_path, [gnome([8, 10])], game)
    assert code == 0
    assert [label for state, label in game.chosen if state == "roll"] == \
        ["ROLL AGAIN", "ROLL AGAIN", "KEEP"]


def test_a_band_never_met_ends_with_a_refusal_naming_the_rolls(tmp_path):
    code, _sess, game, out, summary = drive(
        tmp_path, [gnome([8, 10])], FakeGame(tmp_path, rolls=[con_roll(14)]),
        max_rolls=5)
    assert code == 1
    assert "[8, 10]" in summary["lost"] and "5 rolls" in summary["lost"]
    assert "lowest was 14" in summary["lost"]
    assert [label for state, label in game.chosen if state == "roll"] == \
        ["ROLL AGAIN"] * 4
    logged = [json.loads(ln) for ln in
              (out / "run.jsonl").read_text().splitlines()]
    assert [r["attempt"] for r in logged if r.get("event") == "roll"
            or r.get("kind") == "roll"] == [1, 2, 3, 4, 5]


@pytest.mark.parametrize("race, band", [
    ("DWARF", [8, 10]), ("DWARF", [8, 11]), ("GNOME", [4, 6]),
    ("GNOME", [19, 19]), ("HALFLING", [8, 9]), ("HUMAN", [10, 8])])
def test_a_band_the_race_cannot_roll_is_refused_before_any_key(tmp_path, race,
                                                               band):
    with pytest.raises(ValueError):
        creation.Spec.from_json({
            "name": "VICE", "race": race, "gender": "MALE",
            "class": "FIGHTER", "alignment": "LAWFUL GOOD",
            "constitution": band})


@pytest.mark.parametrize("race, band", [
    ("GNOME", [8, 10]), ("HALFLING", [10, 10]), ("DWARF", [12, 13]),
    ("HUMAN", [3, 5])])
def test_a_band_the_race_can_roll_is_accepted(race, band):
    got = creation.Spec.from_json({
        "name": "VICE", "race": race, "gender": "MALE", "class": "FIGHTER",
        "alignment": "LAWFUL GOOD", "constitution": band})
    assert got.constitution == tuple(band)


# -- check_records ------------------------------------------------------------------


def checked(tmp_path, mutate=None, where="both", exceptional=0):
    """The records check on one character; MUTATE alters the record on the
    export, the slot or both, so each side is proved to be compared."""
    sp = PAIR[0]
    exported, slotted = (record(sp, ROLLS[0], exceptional) for _ in range(2))
    if mutate:
        if where in ("export", "both"):
            mutate(exported)
        if where in ("party", "both"):
            mutate(slotted)
    disk([exported], names=[sp.name]).save(str(tmp_path / "rolled.D64"))
    disk([slotted], party=True, exports=False).save(str(tmp_path / "party.D64"))
    return creation.check_records(tmp_path / "rolled.D64",
                                  tmp_path / "party.D64", [sp],
                                  {"VICEFTR": ROLLS[0]})


def test_matching_records_pass(tmp_path):
    assert checked(tmp_path)[-1] == "all records match the spec"


#: Every field `_expected` compares, with a value the spec does not ask for.
MUTATIONS = [
    ("name", "VICEFTX"), ("race", 2), ("sex", 1), ("alignment", 3),
    ("class_bits", 1), ("level_fighter", 2), ("level", 2), ("experience", 5),
    ("strength", 16), ("intelligence", 3), ("wisdom", 3), ("dexterity", 3),
    ("constitution", 3), ("charisma", 3),
    ("save_paralysis", 1), ("save_petrification", 1), ("save_wands", 1),
    ("save_breath", 1), ("save_spell", 1),
]


@pytest.mark.parametrize("where", ["export", "party"])
@pytest.mark.parametrize("field, value", MUTATIONS)
def test_a_wrong_field_on_either_disk_is_rejected(tmp_path, field, value, where):
    lines = checked(tmp_path, lambda r: r.set(field, value), where)
    other = "party" if where == "export" else "export"
    assert lines[-1] == "SPEC MISMATCH"
    bad = [ln for ln in lines if f"VICEFTR {where}:" in ln]
    assert len(bad) == 1 and not bad[0].endswith("ok")
    assert [ln for ln in lines if f"VICEFTR {other}:" in ln][0].endswith("ok")


def test_every_compared_field_has_a_mutation():
    compared = set(creation._expected(PAIR[0], ROLLS[0]))
    covered = {"class_levels" if f == "level_fighter" else f for f, _ in MUTATIONS}
    assert compared == covered


def test_exceptional_strength_is_not_compared(tmp_path):
    """The roll screen never shows it: it is rolled after the alignment."""
    assert checked(tmp_path, exceptional=99)[-1] == "all records match the spec"


def test_a_character_with_no_roll_is_a_mismatch(tmp_path):
    checked(tmp_path)
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", PAIR[:1], {})
    assert lines[-1] == "SPEC MISMATCH" and "no roll was read" in lines[0]


def test_a_duplicate_name_is_a_mismatch(tmp_path):
    checked(tmp_path)
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", [PAIR[0], PAIR[0]],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "named twice" in lines[0]


def test_a_missing_export_is_a_mismatch(tmp_path):
    sp = PAIR[0]
    write_disks(tmp_path, [])
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", [sp],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "MISSING" in lines[0]
    assert "no such file" in lines[0]     # the read failure is shown, not hidden


@pytest.mark.parametrize("gone", ["rolled.D64", "party.D64"])
def test_a_disk_that_cannot_be_opened_is_a_mismatch_not_a_raise(tmp_path, gone):
    checked(tmp_path)
    (tmp_path / gone).unlink()
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", PAIR[:1],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH"
    assert f"{gone}: cannot be read" in lines[0] and "MISMATCH" in lines[0]


def test_a_party_disk_with_no_savegame_is_a_mismatch_not_a_raise(tmp_path):
    checked(tmp_path)
    D64.blank().save(str(tmp_path / "party.D64"))
    lines = creation.check_records(tmp_path / "rolled.D64",
                                   tmp_path / "party.D64", PAIR[:1],
                                   {"VICEFTR": ROLLS[0]})
    assert lines[-1] == "SPEC MISMATCH" and "party.D64: cannot be read" in lines[0]


@pytest.mark.parametrize("bad", [
    {"name": "TOO LONG A NAME FOR IT", "race": "HUMAN", "gender": "MALE",
     "class": "FIGHTER", "alignment": "LAWFUL GOOD"},
    {"name": "VICE", "race": "ORC", "gender": "MALE", "class": "FIGHTER",
     "alignment": "LAWFUL GOOD"},
    {"name": "VICE", "race": "HUMAN", "gender": "MALE", "class": "PALADIN",
     "alignment": "LAWFUL GOOD"},
])
def test_a_spec_the_screens_cannot_take_is_refused(bad):
    with pytest.raises(ValueError):
        creation.Spec.from_json(bad)


def test_lists_writes_every_races_classes_and_each_classs_alignments(tmp_path):
    game = FakeGame(tmp_path)
    sess = FakeSession(game)
    clock = Clock()
    out = tmp_path / "run"
    code = creation.run(sess, out, lists=True, clock=clock, sleep=clock.sleep)
    summary = json.loads((out / "summary.json").read_text())
    assert code == 0, summary["lost"]
    lists = json.loads((out / "lists.json").read_text())
    assert lists["classes"]["ELF"] == CLASSES["ELF"]
    assert "LAWFUL GOOD" not in lists["alignments"]["THIEF"]
    assert len(lists["alignments"]["FIGHTER"]) == 9
    assert lists["skipped"] == {}
    assert "LAWFUL GOOD" not in lists["alignments"]["MAGIC-USER/THIEF"]
    assert game.state == "party"


# -- the screens the game drew ---------------------------------------------------
#
# Each entry is a screen a real Stage 1 or Stage 3 boot captured: its name, the
# state the driver must read it as, the text of every row that holds anything
# but the window's frame, and the highlighted runs of each row (colour 1).  The
# rest of a screen is blank inside the frame.  Every row of the window carries
# the frame -- a `$` in the first and last column -- so a reader that starts at
# column 0 or ends at column 39 is caught here and not on a boot.

RECORDED = [
    ('party menu, empty', 'party',
     '001-00-partymenu.txt',
     {
         2: '$NAME                            AC HP $',
         13: '$ CREATE NEW CHARACTER                 $',
         14: '$ ADD CHARACTER TO PARTY               $',
         15: '$ LOAD SAVED GAME                      $',
     },
     {2: [(1, 4), (33, 37)], 13: [(2, 21)]}),
    ('race list', 'race',
     '002-01-race-list.txt',
     {
         2: '$ DWARF                                $',
         3: '$ ELF                                  $',
         4: '$ GNOME                                $',
         5: '$ HALF-ELF                             $',
         6: '$ HALFLING                             $',
         7: '$ HUMAN                                $',
         8: '$ EXIT                                 $',
         11: '$PICK RACE                             $',
     },
     {2: [(2, 6)]}),
    ('gender list', 'gender',
     '020-L-DWARF-male.txt',
     {
         2: '$ MALE                                 $',
         3: '$ FEMALE                               $',
         6: '$PICK GENDER                           $',
     },
     {2: [(2, 5)]}),
    ('roll screen', 'roll',
     '236-C-roll-down.txt',
     {
         2: '$RACE HUMAN                            $',
         3: '$GENDER MALE                           $',
         5: '$STRENGTH      17                      $',
         6: '$INTELLIGENCE  16                      $',
         7: '$WISDOM        15                      $',
         8: '$DEXTERITY     14                      $',
         9: '$CONSTITUTION  16                      $',
         10: '$CHARISMA      13                      $',
         12: '$ ROLL AGAIN                           $',
         13: '$ KEEP                                 $',
     },
     {12: [(2, 11)]}),
    ('class list, elf', 'class',
     '075-L-ELF-class-back.txt',
     {
         2: '$FIGHTER                               $',
         3: '$MAGIC-USER                            $',
         4: '$THIEF                                 $',
         5: '$FIGHTER/MAGIC-USER                    $',
         6: '$FIGHTER/THIEF                         $',
         7: '$FIGHTER/MAGIC-USER/THIEF              $',
         8: '$MAGIC-USER/THIEF                      $',
         10: '$PICK CLASS                            $',
     },
     {2: [(1, 38)]}),
    ('alignment list', 'alignment',
     '240-C-align-lg.txt',
     {
         2: '$ LAWFUL GOOD                          $',
         3: '$ LAWFUL NEUTRAL                       $',
         4: '$ LAWFUL EVIL                          $',
         5: '$ NEUTRAL GOOD                         $',
         6: '$ TRUE NEUTRAL                         $',
         7: '$ NEUTRAL EVIL                         $',
         8: '$ CHAOTIC GOOD                         $',
         9: '$ CHAOTIC NEUTRAL                      $',
         10: '$ CHAOTIC EVIL                         $',
         13: '$PICK ALIGNMENT                        $',
     },
     {2: [(2, 12)]}),
    ('name prompt', 'name',
     '242-C-name-return.txt',
     {
         2: '$INPUT NAME OF CHARACTER               $',
         3: '$ VICEFTR£                             $',
     },
     {}),
    ('character sheet', 'sheet',
     '243-C-save-prompt.txt',
     {
         1: '$VICEFTR                               $',
         3: '$MALE HUMAN AGE 21                     $',
         4: '$LAWFUL GOOD                           $',
         5: '$FIGHTER                               $',
         7: '$STR 17     GOLD     150               $',
         8: '$INT 16                                $',
         9: '$WIS 15                                $',
         10: '$DEX 14                                $',
         11: '$CON 16                                $',
         12: '$CHR 13                                $',
         13: '$                           SAVE?      $',
         14: '$LEVEL 1    EXP 0                      $',
         15: '$HITPOINTS 11               YES        $',
         16: '$                           NO         $',
         17: '$AC 9                                  $',
         20: '$THACO 19  DAMAGE 1D2+1                $',
         22: '$OK                                    $',
     },
     {3: [(1, 4), (6, 10), (12, 14), (16, 17)], 4: [(1, 11)], 5: [(1, 7)], 14: [(1, 5), (7, 7), (12, 14), (16, 16)], 15: [(1, 9), (28, 30)]}),
    ('portrait bar', 'portrait',
     '245-C-portrait-right1.txt',
     {
         24: 'CHANGE:HEAD BODY KEEP',
     },
     {24: [(7, 10)]}),
    ('icon bar', 'icon',
     '251-C-icon-exit.txt',
     {
         24: 'ICON:PARTS COLOR SIZE EXIT',
     },
     {24: [(22, 25)]}),
    ('save disk prompt', 'disk',
     '252-C-savedisk-prompt.txt',
     {
         24: 'INSERT YOUR SAVE GAME DISK',
     },
     {}),
    ('add list', 'add',
     '264-A-add-down.txt',
     {
         2: '$  *VICEFTR                            $',
         3: '$   EXIT                               $',
         5: '$ADD CHARACTER TO PARTY                $',
     },
     {2: [(3, 10)]}),
    ('party menu, full', 'party',
     '271-S-save-open.txt',
     {
         2: '$NAME                            AC HP $',
         4: '$VICEFTR                          9 11 $',
         13: '$ CREATE NEW CHARACTER                 $',
         14: '$ DROP CHARACTER                       $',
         15: '$ MODIFY CHARACTER                     $',
         16: '$ VIEW CHARACTER                       $',
         17: '$ ADD CHARACTER TO PARTY               $',
         18: '$ REMOVE CHARACTER FROM PARTY          $',
         19: '$ SAVE CURRENT GAME                    $',
         20: '$ BEGIN ADVENTURING                    $',
     },
     {2: [(1, 4), (33, 37)], 19: [(2, 18)]}),
    ('save bar', 'save-yn',
     '272-S-save-yes.txt',
     {
         2: '$NAME                            AC HP $',
         4: '$VICEFTR                          9 11 $',
         13: '$ CREATE NEW CHARACTER                 $',
         14: '$ DROP CHARACTER                       $',
         15: '$ MODIFY CHARACTER                     $',
         16: '$ VIEW CHARACTER                       $',
         17: '$ ADD CHARACTER TO PARTY               $',
         18: '$ REMOVE CHARACTER FROM PARTY          $',
         19: '$ SAVE CURRENT GAME                    $',
         20: '$ BEGIN ADVENTURING                    $',
         24: 'SAVE GAME: YES NO',
     },
     {2: [(1, 4), (33, 37)], 24: [(11, 13)]}),
    ('saving', 'saving',
     '296-W-saving-stall.txt',
     {
         24: 'SAVING',
     },
     {}),
    ('game disk 3 prompt', 'disk',
     '297-W-gamedisk3-prompt.txt',
     {
         18: '$INSERT YOUR GAME DISK #3              $',
         24: 'PRESS ANY KEY TO CONTINUE',
     },
     {}),
    ('side 3 prompt', 'disk',
     '276-B-side3-prompt.txt',
     {
         18: '$OUTWARD BOUND ...                     $',
         24: 'INSERT SIDE # 3, AND PRESS ANY KEY.',
     },
     {}),
    ('world', 'world',
     '287-W-world.txt',
     {
         24: 'MOVE VIEW CAST AREA ENCAMP SEARCH LOOK',
     },
     {24: [(0, 3)]}),
    ('camp menu', None,
     '295-W-savegame.txt',
     {
         24: 'SAVE GAME  EXIT',
     },
     {24: [(0, 9)]}),
    ('race list, boot', 'race',
     '002-CREATE-NEW-CHARACTER-then.txt',
     {
         2: '$ DWARF                                $',
         3: '$ ELF                                  $',
         4: '$ GNOME                                $',
         5: '$ HALF-ELF                             $',
         6: '$ HALFLING                             $',
         7: '$ HUMAN                                $',
         8: '$ EXIT                                 $',
         11: '$PICK RACE                             $',
     },
     {}),
    ('gender list, boot', 'gender',
     '003-VICEFTR-race.txt',
     {
         2: '$ MALE                                 $',
         3: '$ FEMALE                               $',
         6: '$PICK GENDER                           $',
     },
     {}),
    ('lost roll, boot', 'roll',
     '005-lost-roll.txt',
     {
         2: '$RACE HUMAN                            $',
         3: '$GENDER MALE                           $',
         5: '$STRENGTH      15                      $',
         6: '$INTELLIGENCE  16                      $',
         7: '$WISDOM        14                      $',
         8: '$DEXTERITY     15                      $',
         9: '$CONSTITUTION  17                      $',
         10: '$CHARISMA      12                      $',
         12: '$ ROLL AGAIN                           $',
         13: '$ KEEP                                 $',
     },
     {}),
]


def _codes(ch):
    return {"@": 0, "[": 27, "\u00a3": 28, "]": 29, "^": 30, "_": 31}.get(
        ch, ord(ch) - 64 if "A" <= ch <= "Z" else ord(ch))


def recorded_screen(rows, hot):
    """The `Screen` a captured entry describes: the window frame's rules on
    rows 0 and 23, the rows given, colour 5 except the highlighted runs."""
    lines = {0: "@" + "[" * 38 + "@", 23: "@" + "[" * 38 + "@", **rows}
    codes = bytearray(0x20 for _ in range(25 * COLS))
    colours = bytearray(5 for _ in range(25 * COLS))
    for r, text in lines.items():
        assert len(text) <= COLS, (r, text)
        for i, ch in enumerate(text):
            codes[r * COLS + i] = _codes(ch)
    for r, runs in hot.items():
        for a, b in runs:
            for c in range(a, b + 1):
                colours[r * COLS + c] = 1
    return Screen(bytes(codes), bytes(colours), 0x0400)


SCREENS = {name: (kind, recorded_screen(rows, hot))
           for name, kind, _source, rows, hot in RECORDED}


def screen_of(name):
    return SCREENS[name][1]


class KeySent(Exception):
    """A frozen game was sent a key; `.args[0]` is which."""


class FrozenKeyboard:
    def __init__(self, game):
        self.game, self.sent = game, []

    def key(self, name, hold=0.0, gap=0.0):
        self.sent.append(name)
        if self.game.stop:
            raise KeySent(name)
        self.game.index = min(self.game.index + 1, len(self.game.screens) - 1)

    def text(self, s, hold=0.0, gap=0.0):
        self.sent.append("text " + s)

    def screenshot(self, path, **_kw):
        return True


class FrozenSession(S.Session):
    """A `Session` showing recorded screens: one at a time, moving to the next
    when a key is pressed, or stopping the test at the first key."""

    def __init__(self, *names, stop=False):
        self.screens = [screen_of(n) for n in names]
        self.index, self.stop = 0, stop
        self.kbd = FrozenKeyboard(self)
        self.here = "/nowhere"
        self.save_disk = "/nowhere/SIDE0.D64"

    def screen(self):
        return self.screens[self.index]

    def confirm_bar(self, row=24, was=""):
        self.kbd.key("Return")

    def press_kernal(self, code):
        self.kbd.key(f"kernal {code:#x}")

    def handle_prompt(self, s=None):
        return False


def frozen_driver(tmp_path, *names, stop=False):
    sess = FrozenSession(*names, stop=stop)
    clock = Clock()
    log = creation.runlog.Log(tmp_path / "run.jsonl")
    drv = creation.Driver(sess, tmp_path, log, clock=clock, sleep=clock.sleep)
    return drv, sess


#: The state Stage 1 recorded each screen in, by the row it reads.
def test_every_recorded_screen_is_the_state_stage_one_recorded():
    wrong = {name: creation.recognise(FrozenSession(name), screen)
             for name, (kind, screen) in SCREENS.items()
             if creation.recognise(FrozenSession(name), screen) != kind}
    assert not wrong


ROLLS_SEEN = {
    "roll screen": dict(strength=17, intelligence=16, wisdom=15, dexterity=14,
                        constitution=16, charisma=13),
    "lost roll, boot": dict(strength=15, intelligence=16, wisdom=14,
                            dexterity=15, constitution=17, charisma=12),
}


@pytest.mark.parametrize("name", ROLLS_SEEN)
def test_the_roll_screen_inside_its_frame_reads_six_scores(name):
    assert creation.scores(screen_of(name)) == ROLLS_SEEN[name]


@pytest.mark.parametrize("name", ROLLS_SEEN)
def test_the_driver_keeps_the_roll_the_screen_shows(tmp_path, name):
    drv, sess = frozen_driver(tmp_path, name, name)
    assert drv.read_scores(screen_of(name)) == ROLLS_SEEN[name]


LISTS_SEEN = {
    "race list": ["DWARF", "ELF", "GNOME", "HALF-ELF", "HALFLING", "HUMAN",
                  "EXIT"],
    "race list, boot": ["DWARF", "ELF", "GNOME", "HALF-ELF", "HALFLING",
                        "HUMAN", "EXIT"],
    "gender list": ["MALE", "FEMALE"],
    "gender list, boot": ["MALE", "FEMALE"],
    "class list, elf": CLASSES["ELF"],
    "alignment list": list(creation.ALIGNMENTS),
    "add list": ["VICEFTR", "EXIT"],
}


@pytest.mark.parametrize("name", LISTS_SEEN)
def test_a_framed_list_reads_its_labels_and_nothing_of_the_frame(name):
    kind = SCREENS[name][0]
    assert creation.entries(screen_of(name), kind) == LISTS_SEEN[name]


@pytest.mark.parametrize("name", [n for n in LISTS_SEEN
                                  if SCREENS[n][0] in creation.EXACT_LISTS])
def test_every_label_of_a_framed_list_is_a_whole_row(name):
    s = screen_of(name)
    assert all(S.Session._exact_hit(s, label) is not None
               for label in LISTS_SEEN[name])


def label_row(s, label):
    return S.Session._exact_hit(s, label)[0] if S.Session._exact_hit(
        s, label) else s.find(label)[0]


@pytest.mark.parametrize("name", [n for n in LISTS_SEEN if SCREENS[n][1]
                                  .highlighted_rows(column=2)
                                  or SCREENS[n][1].highlighted_rows(column=1)
                                  or SCREENS[n][1].highlighted_rows(column=4)])
def test_the_highlight_is_walked_by_the_recorded_screens_own_colours(
        tmp_path, name):
    """From the row the game highlighted, every label is reached: Return on
    its own row, Down for a row below, and never a silent timeout."""
    kind, s = SCREENS[name]
    label_col = creation.LISTS[kind][1] if kind != creation.ADD_LIST \
        else creation.ADD_COLUMN
    drv, sess = frozen_driver(tmp_path, name, stop=True)
    here = s.highlighted_rows(column=label_col)
    assert len(here) == 1, here
    for label in LISTS_SEEN[name]:
        sess.kbd.sent.clear()
        with pytest.raises(KeySent) as sent:
            drv.choose(s, kind, label, creation.PARTY_MENU, column=label_col)
        want = label_row(s, label)
        assert sent.value.args[0] == (
            "Return" if want == here[0] else "Down" if want > here[0] else "Up")


def test_the_party_menu_is_walked_from_the_highlight_it_shows(tmp_path):
    kind, s = SCREENS["party menu, empty"]
    drv, sess = frozen_driver(tmp_path, "party menu, empty", stop=True)
    with pytest.raises(KeySent) as sent:
        drv.choose(s, creation.PARTY_MENU, "CREATE NEW CHARACTER",
                   creation.PICK_RACE)
    assert sent.value.args[0] == "Return"
    with pytest.raises(KeySent) as sent:
        drv.choose(s, creation.PARTY_MENU, "LOAD SAVED GAME", creation.PICK_RACE)
    assert sent.value.args[0] == "Down"


def test_the_roll_bar_is_walked_from_the_highlight_it_shows(tmp_path):
    kind, s = SCREENS["roll screen"]
    drv, sess = frozen_driver(tmp_path, "roll screen", stop=True)
    with pytest.raises(KeySent) as sent:
        drv.choose(s, creation.ROLL, "KEEP", creation.PICK_CLASS,
                   column=creation.ROLL_COLUMN)
    assert sent.value.args[0] == "Down"


def test_the_sheet_answer_is_walked_from_the_highlight_it_shows(tmp_path):
    kind, s = SCREENS["character sheet"]
    drv, sess = frozen_driver(tmp_path, "character sheet", stop=True)
    with pytest.raises(KeySent) as sent:
        drv.choose(s, creation.SHEET, "YES", creation.PORTRAIT,
                   column=creation.YES_COLUMN)
    assert sent.value.args[0] == "Return"


@pytest.mark.parametrize("name,label,key", [
    ("portrait bar", "KEEP", "Right"),
    ("icon bar", "EXIT", "Return"),
    ("save bar", "YES", "Return"),
    ("save bar", "NO", "Right"),
])
def test_a_bar_is_walked_from_the_highlight_it_shows(tmp_path, name, label, key):
    kind, s = SCREENS[name]
    drv, sess = frozen_driver(tmp_path, name, stop=True)
    with pytest.raises(KeySent) as sent:
        drv.choose_bar(s, kind, label, creation.PARTY_MENU)
    assert sent.value.args[0] == key


def test_a_typed_name_is_found_on_the_name_row(tmp_path):
    drv, sess = frozen_driver(tmp_path, "name prompt", "character sheet")
    s = drv.name_it(screen_of("name prompt"), "VICEFTR")
    assert creation.recognise(sess, s) == creation.SHEET


def test_a_starred_name_is_found_on_the_add_list(tmp_path):
    drv, sess = frozen_driver(tmp_path, "add list")
    assert drv.starred("VICEFTR") is screen_of("add list")


def test_every_screen_the_driver_waits_for_has_a_recorded_one():
    seen = {kind for kind, _ in SCREENS.values()}
    waited = {creation.PARTY_MENU, creation.PICK_RACE, creation.PICK_GENDER,
              creation.ROLL, creation.PICK_CLASS, creation.PICK_ALIGN,
              creation.NAME, creation.SHEET, creation.PORTRAIT, creation.ICON,
              creation.ADD_LIST, creation.SAVE_YN, creation.SAVING,
              creation.WORLD, creation.DISK}
    assert waited <= seen, waited - seen


def test_a_screen_the_creation_driver_does_not_wait_for_is_not_recognised():
    assert creation.recognise(FrozenSession("camp menu"),
                              screen_of("camp menu")) is None


def test_the_fake_game_draws_the_frame_on_every_screen(tmp_path):
    """The fake's every screen, not only its lists, carries the window frame;
    a reader that cannot cope with it fails the whole scripted suite."""
    game = FakeGame(tmp_path)
    for state in ("party", "race", "gender", "roll", "class", "align", "name",
                  "sheet", "add", "saving", "junk"):
        game.state = state
        game.pick = {"race": "HUMAN", "gender": "MALE", "class": "FIGHTER"}
        game.roll = dict(ROLLS[0])
        screen = game.render()
        assert all(screen.row(r)[0] == "$" == screen.row(r)[-1]
                   for r in range(1, 23)), state
        assert screen.row(0)[0] == "@" == screen.row(23)[0], state


CAPTURES = (pathlib.Path.home() / ".cache" / "wish" / "acceptance" / "722")


def capture_screen(path):
    """A `Screen` from a `shots/*.txt` a boot wrote: numbered rows over a row of
    colour digits, or the plain rows the driver's own `capture` writes. A file
    cut short or not text raises `ValueError`."""
    import re
    lines = path.read_text(encoding="utf-8").split("\n")
    rows, colours = [" " * COLS] * 25, [[5] * COLS for _ in range(25)]
    if lines and re.match(r"\s*0 \|", lines[0]):
        for i, line in enumerate(lines):
            m = re.match(r"\s*(\d+) \|(.{40})\|$", line)
            if m:
                digits = (re.match(r"\s+\|(.{40})\|$", lines[i + 1])
                          if i + 1 < len(lines) else None)
                if digits is None:
                    raise ValueError(f"{path.name}: row {m.group(1)} has no colour row")
                rows[int(m.group(1))] = m.group(2)
                colours[int(m.group(1))] = [int(c, 16) for c in digits.group(1)]
    else:
        rows = [r.ljust(COLS)[:COLS] for r in lines[:25]]
        rows += [" " * COLS] * (25 - len(rows))
    return Screen(bytes(_codes(ch) for r in rows for ch in r),
                  bytes(c for r in colours for c in r), 0x0400)


def sweep_captures(shots):
    """Problems found in the readable captures, and the names of those that
    could not be read (a boot cut short leaves a partial file)."""
    problems, unreadable = [], []
    for path in shots:
        try:
            if path.read_text(encoding="utf-8").startswith("(bitmap)"):
                continue
            s = capture_screen(path)
        except ValueError:
            unreadable.append(path.name)
            continue
        kind = creation.recognise(FrozenSession(), s)
        if kind == creation.ROLL and len(creation.scores(s)) != 6:
            problems.append(f"{path.name}: roll with {creation.scores(s)}")
        if kind in creation.EXACT_LISTS:
            for label in creation.entries(s, kind):
                if "$" in label or S.Session._exact_hit(s, label) is None:
                    problems.append(f"{path.name}: {label!r} is not a whole row")
    return problems, unreadable


def test_every_captured_creation_screen_reads_as_the_state_it_shows():
    """The whole recorded set, when the captures are on this machine: a roll
    screen has six scores, a list has whole-row labels, and no label carries
    the frame."""
    shots = sorted(CAPTURES.glob("*/shots/*.txt"))
    if not shots:
        pytest.skip("the Stage 1 and Stage 3 captures are not on this machine")
    problems, _unreadable = sweep_captures(shots)
    assert not problems, problems[:10]


def test_a_truncated_capture_is_reported_unreadable_not_raised(tmp_path):
    """A boot cut short leaves a numbered row with no colour row, a file
    without its digit rows, or bytes that are not text; the sweep names each
    and goes on."""
    row = "  1 |" + "A" * 40 + "|"
    (tmp_path / "cut.txt").write_text("  0 |" + " " * 40 + "|\n" + " " * 5 + "|"
                                      + "5" * 40 + "|\n" + row)
    (tmp_path / "nodigits.txt").write_text("  0 |" + " " * 40 + "|\nnot a row\n"
                                           + row + "\nx\n" + row)
    (tmp_path / "binary.txt").write_bytes(b"\xff\xfe\x00\x80")
    problems, unreadable = sweep_captures(sorted(tmp_path.glob("*.txt")))
    assert problems == []
    assert unreadable == ["binary.txt", "cut.txt", "nodigits.txt"]


def _framed_screen(row_text, colours_by_col, framed=True):
    """A screen whose row 5 is *row_text* between `$` frame cells (or not)."""
    to_code = {v: k for k, v in reversed(list(_SCREEN_TO_ASCII.items()))}
    codes = [0x20] * (SCREEN_COLS * SCREEN_ROWS)
    colours = [5] * len(codes)
    line = ("$" + row_text.ljust(SCREEN_COLS - 2) + "$") if framed else row_text
    for c, ch in enumerate(line):
        codes[5 * SCREEN_COLS + c] = to_code[ch]
        colours[5 * SCREEN_COLS + c] = colours_by_col.get(c, 5)
    return Screen(bytes(codes), bytes(colours), 0x0400)


def test_a_framed_row_holding_only_a_highlighted_label_reads_as_highlighted():
    s = _framed_screen(" NO", {2: 1, 3: 1}, framed=True)
    assert s.row_colour(5) == 1
    assert s.highlighted_rows() == [5]


def test_an_unframed_row_still_counts_every_cell():
    s = _framed_screen("NO", {0: 1, 1: 1}, framed=False)
    assert s.row_colour(5) == 1


def test_a_row_with_a_frame_on_one_side_only_counts_the_dollar():
    # "$N": the two cells tie, and the first colour counted wins.  Skipping the
    # lone `$` would answer 5.
    s = _framed_screen("$N", {0: 1, 1: 5}, framed=False)
    assert s.row_colour(5) == 1


def test_the_with_column_path_ignores_the_frame_rule():
    s = _framed_screen(" NO", {2: 1, 3: 1}, framed=True)
    assert s.highlighted_rows(column=2) == [5]
    assert s.highlighted_rows(column=10) == []


def test_a_sturdy_races_saves_are_checked_against_its_constitution(tmp_path):
    """A gnome with constitution 9 takes 9 * 2 // 7 = 2 off all five saves."""
    sp = gnome([8, 10])
    roll = con_roll(9)
    plain = record(sp, roll)
    tables = creation.levels.saving_throws(sp.classes, creation.RACES["GNOME"],
                                           9, "pool-of-radiance")
    without = creation.levels.saving_throws(sp.classes, 0, 9,
                                            "pool-of-radiance")
    assert [b - a for a, b in zip(tables, without)] == [2] * 5
    assert [plain.get(f) for f in creation.SAVE_FIELDS] == list(tables)
    disk([plain], names=[sp.name]).save(str(tmp_path / "rolled.D64"))
    disk([plain], party=True, exports=False).save(str(tmp_path / "party.D64"))
    args = (tmp_path / "rolled.D64", tmp_path / "party.D64", [sp])
    assert creation.check_records(*args, {sp.name: roll})[-1] == \
        "all records match the spec"
    # The same record with the two points not taken off: only the saves differ.
    for f, v in zip(creation.SAVE_FIELDS, without):
        plain.set(f, v)
    disk([plain], names=[sp.name]).save(str(tmp_path / "rolled.D64"))
    lines = creation.check_records(*args, {sp.name: roll})
    assert lines[-1] == "SPEC MISMATCH"
    bad = [ln.split("MISMATCH: ")[1] for ln in lines if "export:" in ln]
    assert all(m.startswith("save_") for m in bad[0].split("; "))
