# Form implementation generated from reading ui file '/home/donald/src/wish/editor/convert.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConvertDialog(object):
    def setupUi(self, ConvertDialog):
        ConvertDialog.setObjectName("ConvertDialog")
        ConvertDialog.resize(680, 480)
        ConvertDialog.setWindowTitle("")
        self.outer_layout = QtWidgets.QVBoxLayout(ConvertDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.form = QtWidgets.QFormLayout()
        self.form.setObjectName("form")
        self.label_source = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_source.setObjectName("label_source")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_source)
        self.source_row = QtWidgets.QHBoxLayout()
        self.source_row.setObjectName("source_row")
        self.convert_source = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_source.setObjectName("convert_source")
        self.source_row.addWidget(self.convert_source)
        self.convert_choose_source = QtWidgets.QPushButton(parent=ConvertDialog)
        self.convert_choose_source.setObjectName("convert_choose_source")
        self.source_row.addWidget(self.convert_choose_source)
        self.source_row.setStretch(0, 1)
        self.form.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.source_row)
        self.label_to = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_to.setObjectName("label_to")
        self.form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_to)
        self.convert_destination = QtWidgets.QComboBox(parent=ConvertDialog)
        self.convert_destination.setObjectName("convert_destination")
        self.form.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.convert_destination)
        self.label_game = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_game.setObjectName("label_game")
        self.form.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_game)
        self.game_row = QtWidgets.QHBoxLayout()
        self.game_row.setObjectName("game_row")
        self.convert_game = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_game.setObjectName("convert_game")
        self.game_row.addWidget(self.convert_game)
        self.convert_choose_game = QtWidgets.QPushButton(parent=ConvertDialog)
        self.convert_choose_game.setObjectName("convert_choose_game")
        self.game_row.addWidget(self.convert_choose_game)
        self.game_row.setStretch(0, 1)
        self.form.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.game_row)
        self.label_folder = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_folder.setObjectName("label_folder")
        self.form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_folder)
        self.folder_row = QtWidgets.QHBoxLayout()
        self.folder_row.setObjectName("folder_row")
        self.convert_folder = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_folder.setObjectName("convert_folder")
        self.folder_row.addWidget(self.convert_folder)
        self.convert_choose_folder = QtWidgets.QPushButton(parent=ConvertDialog)
        self.convert_choose_folder.setObjectName("convert_choose_folder")
        self.folder_row.addWidget(self.convert_choose_folder)
        self.folder_row.setStretch(0, 1)
        self.form.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.folder_row)
        self.outer_layout.addLayout(self.form)
        self.convert_report = QtWidgets.QPlainTextEdit(parent=ConvertDialog)
        self.convert_report.setReadOnly(True)
        self.convert_report.setObjectName("convert_report")
        self.outer_layout.addWidget(self.convert_report)
        self.buttons = QtWidgets.QDialogButtonBox(parent=ConvertDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)
        self.outer_layout.setStretch(1, 1)

        self.retranslateUi(ConvertDialog)
        self.buttons.accepted.connect(ConvertDialog.accept) # type: ignore
        self.buttons.rejected.connect(ConvertDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConvertDialog)

    def retranslateUi(self, ConvertDialog):
        pass
