# Form implementation generated from reading ui file '/home/donald/src/wish/editor/convert.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConvertDialog(object):
    def setupUi(self, ConvertDialog):
        ConvertDialog.setObjectName("ConvertDialog")
        ConvertDialog.resize(680, 305)
        ConvertDialog.setWindowTitle("")
        self.outer_layout = QtWidgets.QVBoxLayout(ConvertDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.form = QtWidgets.QFormLayout()
        self.form.setObjectName("form")
        self.label_source = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_source.setObjectName("label_source")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_source)
        self.source_row = QtWidgets.QHBoxLayout()
        self.source_row.setObjectName("source_row")
        self.convert_source = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_source.setObjectName("convert_source")
        self.source_row.addWidget(self.convert_source)
        self.convert_choose_source = QtWidgets.QPushButton(parent=ConvertDialog)
        self.convert_choose_source.setObjectName("convert_choose_source")
        self.source_row.addWidget(self.convert_choose_source)
        self.convert_slot = QtWidgets.QComboBox(parent=ConvertDialog)
        self.convert_slot.setObjectName("convert_slot")
        self.source_row.addWidget(self.convert_slot)
        self.source_row.setStretch(0, 1)
        self.form.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.source_row)
        self.label_to = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_to.setObjectName("label_to")
        self.form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_to)
        self.convert_destination = QtWidgets.QComboBox(parent=ConvertDialog)
        self.convert_destination.setObjectName("convert_destination")
        self.form.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.convert_destination)
        self.label_files = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_files.setObjectName("label_files")
        self.form.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_files)
        self.files_row = QtWidgets.QHBoxLayout()
        self.files_row.setObjectName("files_row")
        self.convert_files = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_files.setObjectName("convert_files")
        self.files_row.addWidget(self.convert_files)
        self.convert_choose_files = QtWidgets.QPushButton(parent=ConvertDialog)
        self.convert_choose_files.setObjectName("convert_choose_files")
        self.files_row.addWidget(self.convert_choose_files)
        self.files_row.setStretch(0, 1)
        self.form.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.files_row)
        self.label_folder = QtWidgets.QLabel(parent=ConvertDialog)
        self.label_folder.setObjectName("label_folder")
        self.form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_folder)
        self.folder_column = QtWidgets.QVBoxLayout()
        self.folder_column.setObjectName("folder_column")
        self.folder_row = QtWidgets.QHBoxLayout()
        self.folder_row.setObjectName("folder_row")
        self.convert_folder = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_folder.setObjectName("convert_folder")
        self.folder_row.addWidget(self.convert_folder)
        self.convert_choose_folder = QtWidgets.QPushButton(parent=ConvertDialog)
        self.convert_choose_folder.setObjectName("convert_choose_folder")
        self.folder_row.addWidget(self.convert_choose_folder)
        self.folder_row.setStretch(0, 1)
        self.folder_column.addLayout(self.folder_row)
        self.convert_destination_line = QtWidgets.QLabel(parent=ConvertDialog)
        self.convert_destination_line.setObjectName("convert_destination_line")
        self.folder_column.addWidget(self.convert_destination_line)
        self.form.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.folder_column)
        self.outer_layout.addLayout(self.form)
        self.buttons = QtWidgets.QDialogButtonBox(parent=ConvertDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)

        self.retranslateUi(ConvertDialog)
        self.buttons.accepted.connect(ConvertDialog.accept) # type: ignore
        self.buttons.rejected.connect(ConvertDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConvertDialog)

    def retranslateUi(self, ConvertDialog):
        pass
