# Form implementation generated from reading ui file '/home/donald/src/wish/editor/dosimport.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DosImportDialog(object):
    def setupUi(self, DosImportDialog):
        DosImportDialog.setObjectName("DosImportDialog")
        DosImportDialog.resize(680, 480)
        self.outer_layout = QtWidgets.QVBoxLayout(DosImportDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.form = QtWidgets.QFormLayout()
        self.form.setObjectName("form")
        self.label_folder = QtWidgets.QLabel(parent=DosImportDialog)
        self.label_folder.setObjectName("label_folder")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_folder)
        self.dos_folder = QtWidgets.QLabel(parent=DosImportDialog)
        self.dos_folder.setObjectName("dos_folder")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dos_folder)
        self.label_slot = QtWidgets.QLabel(parent=DosImportDialog)
        self.label_slot.setObjectName("label_slot")
        self.form.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_slot)
        self.dos_slot = QtWidgets.QComboBox(parent=DosImportDialog)
        self.dos_slot.setObjectName("dos_slot")
        self.form.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dos_slot)
        self.dos_report = QtWidgets.QPlainTextEdit(parent=DosImportDialog)
        self.dos_report.setReadOnly(True)
        self.dos_report.setObjectName("dos_report")
        self.form.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.dos_report)
        self.label_destination = QtWidgets.QLabel(parent=DosImportDialog)
        self.label_destination.setObjectName("label_destination")
        self.form.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_destination)
        self.where = QtWidgets.QHBoxLayout()
        self.where.setObjectName("where")
        self.dos_destination = QtWidgets.QLineEdit(parent=DosImportDialog)
        self.dos_destination.setObjectName("dos_destination")
        self.where.addWidget(self.dos_destination)
        self.dos_browse = QtWidgets.QPushButton(parent=DosImportDialog)
        self.dos_browse.setObjectName("dos_browse")
        self.where.addWidget(self.dos_browse)
        self.where.setStretch(0, 1)
        self.form.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.where)
        self.outer_layout.addLayout(self.form)
        self.buttons = QtWidgets.QDialogButtonBox(parent=DosImportDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)
        self.outer_layout.setStretch(0, 1)

        self.retranslateUi(DosImportDialog)
        self.buttons.accepted.connect(DosImportDialog.accept) # type: ignore
        self.buttons.rejected.connect(DosImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DosImportDialog)

    def retranslateUi(self, DosImportDialog):
        _translate = QtCore.QCoreApplication.translate
        DosImportDialog.setWindowTitle(_translate("DosImportDialog", "Import a DOS save"))
        self.label_folder.setText(_translate("DosImportDialog", "DOS save"))
        self.label_slot.setText(_translate("DosImportDialog", "Slot"))
        self.label_destination.setText(_translate("DosImportDialog", "Save as"))
        self.dos_browse.setText(_translate("DosImportDialog", "Browse…"))
