# Form implementation generated from reading ui file 'editor/exports.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExportDialog(object):
    def setupUi(self, ExportDialog):
        ExportDialog.setObjectName("ExportDialog")
        ExportDialog.resize(680, 480)
        ExportDialog.setWindowTitle("")
        self.outer_layout = QtWidgets.QVBoxLayout(ExportDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.form = QtWidgets.QFormLayout()
        self.form.setObjectName("form")
        self.outer_layout.addLayout(self.form)
        self.export_report = QtWidgets.QPlainTextEdit(parent=ExportDialog)
        self.export_report.setReadOnly(True)
        self.export_report.setObjectName("export_report")
        self.outer_layout.addWidget(self.export_report)
        self.buttons = QtWidgets.QDialogButtonBox(parent=ExportDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)
        self.outer_layout.setStretch(1, 1)

        self.retranslateUi(ExportDialog)
        self.buttons.accepted.connect(ExportDialog.accept) # type: ignore
        self.buttons.rejected.connect(ExportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExportDialog)

    def retranslateUi(self, ExportDialog):
        pass
