# Form implementation generated from reading ui file '/home/donald/src/wish/editor/inventory.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddItemDialog(object):
    def setupUi(self, AddItemDialog):
        AddItemDialog.setObjectName("AddItemDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddItemDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search = QtWidgets.QLineEdit(parent=AddItemDialog)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        self.list = QtWidgets.QListWidget(parent=AddItemDialog)
        self.list.setObjectName("list")
        self.verticalLayout.addWidget(self.list)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddItemDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddItemDialog)
        self.buttonBox.accepted.connect(AddItemDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddItemDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddItemDialog)

    def retranslateUi(self, AddItemDialog):
        _translate = QtCore.QCoreApplication.translate
        AddItemDialog.setWindowTitle(_translate("AddItemDialog", "Add an item"))
        self.search.setPlaceholderText(_translate("AddItemDialog", "Type to filter"))
