# Form implementation generated from reading ui file '/home/agent/src/wish/editor/leavebehind.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LeaveBehindDialog(object):
    def setupUi(self, LeaveBehindDialog):
        LeaveBehindDialog.setObjectName("LeaveBehindDialog")
        LeaveBehindDialog.resize(560, 520)
        self.outer_layout = QtWidgets.QVBoxLayout(LeaveBehindDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.heading_label = QtWidgets.QLabel(parent=LeaveBehindDialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.heading_label.setFont(font)
        self.heading_label.setText("")
        self.heading_label.setObjectName("heading_label")
        self.outer_layout.addWidget(self.heading_label)
        self.explanation_label = QtWidgets.QLabel(parent=LeaveBehindDialog)
        self.explanation_label.setText("")
        self.explanation_label.setWordWrap(True)
        self.explanation_label.setObjectName("explanation_label")
        self.outer_layout.addWidget(self.explanation_label)
        self.pack_tree = QtWidgets.QTreeWidget(parent=LeaveBehindDialog)
        self.pack_tree.setRootIsDecorated(False)
        self.pack_tree.setStyleSheet("QTreeView::branch { image: none; }")
        self.pack_tree.setItemsExpandable(False)
        self.pack_tree.setUniformRowHeights(False)
        self.pack_tree.setWordWrap(True)
        self.pack_tree.setHeaderHidden(False)
        self.pack_tree.setObjectName("pack_tree")
        self.pack_tree.headerItem().setText(0, "1")
        self.pack_tree.headerItem().setText(1, "2")
        self.pack_tree.headerItem().setText(2, "3")
        self.pack_tree.headerItem().setText(3, "4")
        self.pack_tree.header().setStretchLastSection(False)
        self.outer_layout.addWidget(self.pack_tree)
        self.remaining_label = QtWidgets.QLabel(parent=LeaveBehindDialog)
        self.remaining_label.setText("")
        self.remaining_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.remaining_label.setObjectName("remaining_label")
        self.outer_layout.addWidget(self.remaining_label)
        self.button_row = QtWidgets.QHBoxLayout()
        self.button_row.setObjectName("button_row")
        self.items_remaining_label = QtWidgets.QLabel(parent=LeaveBehindDialog)
        self.items_remaining_label.setText("")
        self.items_remaining_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.items_remaining_label.setObjectName("items_remaining_label")
        self.button_row.addWidget(self.items_remaining_label)
        self.buttons = QtWidgets.QDialogButtonBox(parent=LeaveBehindDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.button_row.addWidget(self.buttons)
        self.button_row.setStretch(0, 1)
        self.outer_layout.addLayout(self.button_row)
        self.outer_layout.setStretch(2, 1)

        self.retranslateUi(LeaveBehindDialog)
        self.buttons.accepted.connect(LeaveBehindDialog.accept) # type: ignore
        self.buttons.rejected.connect(LeaveBehindDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LeaveBehindDialog)

    def retranslateUi(self, LeaveBehindDialog):
        _translate = QtCore.QCoreApplication.translate
        LeaveBehindDialog.setWindowTitle(_translate("LeaveBehindDialog", "Choose what to leave behind"))
