# Form implementation generated from reading ui file '/home/donald/src/wish/editor/memorised.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MemorisedEditor(object):
    def setupUi(self, MemorisedEditor):
        MemorisedEditor.setObjectName("MemorisedEditor")
        self.outer_layout = QtWidgets.QVBoxLayout(MemorisedEditor)
        self.outer_layout.setContentsMargins(0, 0, 0, 0)
        self.outer_layout.setObjectName("outer_layout")
        self.list = QtWidgets.QListWidget(parent=MemorisedEditor)
        self.list.setObjectName("list")
        self.outer_layout.addWidget(self.list)
        self.choice = QtWidgets.QComboBox(parent=MemorisedEditor)
        self.choice.setObjectName("choice")
        self.outer_layout.addWidget(self.choice)
        self.row = QtWidgets.QHBoxLayout()
        self.row.setObjectName("row")
        self.add = QtWidgets.QPushButton(parent=MemorisedEditor)
        self.add.setObjectName("add")
        self.row.addWidget(self.add)
        self.remove = QtWidgets.QPushButton(parent=MemorisedEditor)
        self.remove.setObjectName("remove")
        self.row.addWidget(self.remove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.row.addItem(spacerItem)
        self.outer_layout.addLayout(self.row)
        self.capacity = QtWidgets.QLabel(parent=MemorisedEditor)
        self.capacity.setWordWrap(True)
        self.capacity.setObjectName("capacity")
        self.outer_layout.addWidget(self.capacity)

        self.retranslateUi(MemorisedEditor)
        QtCore.QMetaObject.connectSlotsByName(MemorisedEditor)

    def retranslateUi(self, MemorisedEditor):
        _translate = QtCore.QCoreApplication.translate
        self.add.setText(_translate("MemorisedEditor", "Add"))
        self.remove.setText(_translate("MemorisedEditor", "Remove"))
