# Form implementation generated from reading ui file '/home/agent/src/wish/editor/namefit.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NameFitDialog(object):
    def setupUi(self, NameFitDialog):
        NameFitDialog.setObjectName("NameFitDialog")
        NameFitDialog.resize(520, 260)
        NameFitDialog.setWindowTitle("")
        self.outer_layout = QtWidgets.QVBoxLayout(NameFitDialog)
        self.outer_layout.setObjectName("outer_layout")
        self.explanation_label = QtWidgets.QLabel(parent=NameFitDialog)
        self.explanation_label.setText("")
        self.explanation_label.setWordWrap(True)
        self.explanation_label.setObjectName("explanation_label")
        self.outer_layout.addWidget(self.explanation_label)
        self.names_table = QtWidgets.QTableWidget(parent=NameFitDialog)
        self.names_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.names_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.names_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.names_table.setShowGrid(False)
        self.names_table.setObjectName("names_table")
        self.names_table.setColumnCount(2)
        self.names_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("1")
        self.names_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("2")
        self.names_table.setHorizontalHeaderItem(1, item)
        self.names_table.horizontalHeader().setVisible(False)
        self.names_table.horizontalHeader().setStretchLastSection(True)
        self.names_table.verticalHeader().setVisible(False)
        self.outer_layout.addWidget(self.names_table)
        self.buttons = QtWidgets.QDialogButtonBox(parent=NameFitDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)
        self.outer_layout.setStretch(1, 1)

        self.retranslateUi(NameFitDialog)
        self.buttons.accepted.connect(NameFitDialog.accept) # type: ignore
        self.buttons.rejected.connect(NameFitDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NameFitDialog)

    def retranslateUi(self, NameFitDialog):
        pass
