# Form implementation generated from reading ui file '/home/donald/src/wish/editor/partspicker.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PartsPicker(object):
    def setupUi(self, PartsPicker):
        PartsPicker.setObjectName("PartsPicker")
        self.outer_layout = QtWidgets.QVBoxLayout(PartsPicker)
        self.outer_layout.setObjectName("outer_layout")
        self.top = QtWidgets.QHBoxLayout()
        self.top.setObjectName("top")
        self.label_size = QtWidgets.QLabel(parent=PartsPicker)
        self.label_size.setObjectName("label_size")
        self.top.addWidget(self.label_size)
        self.size_box = QtWidgets.QComboBox(parent=PartsPicker)
        self.size_box.setObjectName("size_box")
        self.size_box.addItem("")
        self.size_box.addItem("")
        self.top.addWidget(self.size_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top.addItem(spacerItem)
        self.outer_layout.addLayout(self.top)
        self.preview = QtWidgets.QLabel(parent=PartsPicker)
        self.preview.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.preview.setObjectName("preview")
        self.outer_layout.addWidget(self.preview)
        self.lists = QtWidgets.QHBoxLayout()
        self.lists.setObjectName("lists")
        self.column_weapons = QtWidgets.QWidget(parent=PartsPicker)
        self.column_weapons.setObjectName("column_weapons")
        self.layout_weapons = QtWidgets.QVBoxLayout(self.column_weapons)
        self.layout_weapons.setObjectName("layout_weapons")
        self.label_weapon = QtWidgets.QLabel(parent=self.column_weapons)
        self.label_weapon.setObjectName("label_weapon")
        self.layout_weapons.addWidget(self.label_weapon)
        self.weapons = QtWidgets.QListWidget(parent=self.column_weapons)
        self.weapons.setObjectName("weapons")
        self.layout_weapons.addWidget(self.weapons)
        self.lists.addWidget(self.column_weapons)
        self.column_heads = QtWidgets.QWidget(parent=PartsPicker)
        self.column_heads.setObjectName("column_heads")
        self.layout_heads = QtWidgets.QVBoxLayout(self.column_heads)
        self.layout_heads.setObjectName("layout_heads")
        self.label_head = QtWidgets.QLabel(parent=self.column_heads)
        self.label_head.setObjectName("label_head")
        self.layout_heads.addWidget(self.label_head)
        self.heads = QtWidgets.QListWidget(parent=self.column_heads)
        self.heads.setObjectName("heads")
        self.layout_heads.addWidget(self.heads)
        self.lists.addWidget(self.column_heads)
        self.outer_layout.addLayout(self.lists)
        self.buttons = QtWidgets.QDialogButtonBox(parent=PartsPicker)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)

        self.retranslateUi(PartsPicker)
        self.buttons.accepted.connect(PartsPicker.accept) # type: ignore
        self.buttons.rejected.connect(PartsPicker.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PartsPicker)

    def retranslateUi(self, PartsPicker):
        _translate = QtCore.QCoreApplication.translate
        PartsPicker.setWindowTitle(_translate("PartsPicker", "Choose an icon"))
        self.label_size.setText(_translate("PartsPicker", "Size"))
        self.size_box.setItemText(0, _translate("PartsPicker", "small"))
        self.size_box.setItemText(1, _translate("PartsPicker", "large"))
        self.label_weapon.setText(_translate("PartsPicker", "Weapon"))
        self.label_head.setText(_translate("PartsPicker", "Head"))
