# Form implementation generated from reading ui file '/home/agent/src/wish/editor/slotpicker.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SlotPicker(object):
    def setupUi(self, SlotPicker):
        SlotPicker.setObjectName("SlotPicker")
        SlotPicker.resize(360, 110)
        SlotPicker.setWindowTitle("")
        self.outer_layout = QtWidgets.QVBoxLayout(SlotPicker)
        self.outer_layout.setObjectName("outer_layout")
        self.form = QtWidgets.QFormLayout()
        self.form.setObjectName("form")
        self.label_slot = QtWidgets.QLabel(parent=SlotPicker)
        self.label_slot.setObjectName("label_slot")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_slot)
        self.saved_game_slot = QtWidgets.QComboBox(parent=SlotPicker)
        self.saved_game_slot.setObjectName("saved_game_slot")
        self.form.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.saved_game_slot)
        self.outer_layout.addLayout(self.form)
        self.buttons = QtWidgets.QDialogButtonBox(parent=SlotPicker)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Open)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)

        self.retranslateUi(SlotPicker)
        self.buttons.accepted.connect(SlotPicker.accept) # type: ignore
        self.buttons.rejected.connect(SlotPicker.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SlotPicker)

    def retranslateUi(self, SlotPicker):
        _translate = QtCore.QCoreApplication.translate
        self.label_slot.setText(_translate("SlotPicker", "Saved game slot:"))
