# Form implementation generated from reading ui file '/home/donald/src/wish/editor/spellbook.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_SpellbookEditor(object):
    def setupUi(self, SpellbookEditor):
        SpellbookEditor.setObjectName("SpellbookEditor")
        self.outer_layout = QtWidgets.QVBoxLayout(SpellbookEditor)
        self.outer_layout.setContentsMargins(0, 0, 0, 0)
        self.outer_layout.setObjectName("outer_layout")
        self.list = QtWidgets.QListWidget(parent=SpellbookEditor)
        self.list.setObjectName("list")
        self.outer_layout.addWidget(self.list)

        self.retranslateUi(SpellbookEditor)
        QtCore.QMetaObject.connectSlotsByName(SpellbookEditor)

    def retranslateUi(self, SpellbookEditor):
        pass
