# Form implementation generated from reading ui file '/home/donald/src/wish/editor/traitpicker.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TraitPicker(object):
    def setupUi(self, TraitPicker):
        TraitPicker.setObjectName("TraitPicker")
        TraitPicker.resize(520, 560)
        TraitPicker.setWindowTitle("")
        self.outer_layout = QtWidgets.QVBoxLayout(TraitPicker)
        self.outer_layout.setObjectName("outer_layout")
        self.filter_line = QtWidgets.QLineEdit(parent=TraitPicker)
        self.filter_line.setClearButtonEnabled(True)
        self.filter_line.setObjectName("filter_line")
        self.outer_layout.addWidget(self.filter_line)
        self.trait_list = QtWidgets.QTreeWidget(parent=TraitPicker)
        self.trait_list.setRootIsDecorated(False)
        self.trait_list.setUniformRowHeights(True)
        self.trait_list.setHeaderHidden(True)
        self.trait_list.setObjectName("trait_list")
        self.trait_list.headerItem().setText(0, "1")
        self.outer_layout.addWidget(self.trait_list)
        self.buttons = QtWidgets.QDialogButtonBox(parent=TraitPicker)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttons.setObjectName("buttons")
        self.outer_layout.addWidget(self.buttons)
        self.outer_layout.setStretch(1, 1)

        self.retranslateUi(TraitPicker)
        self.buttons.accepted.connect(TraitPicker.accept) # type: ignore
        self.buttons.rejected.connect(TraitPicker.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TraitPicker)

    def retranslateUi(self, TraitPicker):
        pass
