"""Shim: this module moved to `goldbox/dos_codec.py`.

`#470 (Give the project a neutral title beside its neutral character record,
with one port per platform a title shipped on)`'s stage 8 renamed this file so
the platform is the prefix and the role is the noun, beside
`goldbox/c64_codec.py` and `goldbox/amiga_codec.py`. Nothing inside it
changed: every class, constant and function kept its name, and the module is
still the only one that knows a DOS offset.

Two things make the wildcard below insufficient on its own, and the explicit
list is every name it misses rather than a selection somebody judged
important:

* **`goldbox/dos_codec.py` declares an `__all__`, and it names 52 of the 237
  public names the module carries.** A `from ... import *` obeys it, so the
  other 185 would be dropped -- among them `CONVERTS`, `SAVE0_BASE`,
  `SLOT_AREA`, `savgam_writes` and `field_disposition`, every one of which a
  caller reaches as an attribute of this module.
* **A wildcard never carries an underscore name**, and the tests reach 32 of
  them here -- `_ability_pair`, `_where_the_party_is`, `_log` and the rest.

The one deliberate omission is `annotations`, the `__future__` feature object
this file binds for itself. Everything else was checked by identity, all 269
module-level names: `goldbox.dos.X is goldbox.dos_codec.X`.

**Import `goldbox.dos_codec` in anything new.** This module exists to keep the
existing importers working until stage 9 moves them; it is not a place to add
another.
"""

from __future__ import annotations

from .dos_codec import *  # noqa: F401,F403
from .dos_codec import (  # noqa: F401  everything the wildcard cannot carry
    _ABSENT_WHY,
    _COINS,
    _DOS_CLASS_SLOT,
    _INNATE_EFFECTS_TABLES,
    _PAIRED_ABILITY,
    _PERMANENT_FIRST,
    _RACE_COMBAT_EFFECTS_TABLES,
    _THAC0_RECOMPUTE_FROM_PORTS,
    _THIEF_SKILL_COLUMNS,
    _THIEF_SKILL_NAMES,
    _THIEF_SKILL_RECOMPUTE_FROM_PORTS,
    _WRITE_FIELD_DISPOSITION_DERIVED,
    ABILITY_ORDER,
    ANIMATE_AT,
    ANIMATE_FILE,
    ANIMATE_RESIDENT,
    ANIMATE_SIZE,
    BITMAP_BUFFER,
    C64_CLASS_TRAITS,
    CACHE_ANIMATE,
    CACHE_ECL,
    CACHE_GEO,
    CACHE_SQRDATA,
    CACHE_UNSET,
    CACHE_WALLSET,
    CACHE_WALLSET_PIECES,
    CLASS_BY_SLOT,
    CLASS_CODE_FOR_BITS,
    CLASS_CODE_TABLE,
    CLASS_LEVEL_SLOTS,
    CLASS_NUMBERS,
    CLOCK_LIMITS,
    CONSTANTS,
    CONVERTS,
    CURRENT_GEO,
    CURRENT_SCRIPT,
    CURSE_OF_THE_AZURE_BONDS,
    DERIVED,
    DIRECT,
    DISK_HINT,
    DOS_ONLY,
    DROPPED,
    DROPPED_PLAYER_TEXT,
    DUNGEON_SQUARE,
    ECL_DAX,
    EFFECT_ARRAYS,
    EFFECT_NEXT_NULL,
    EFFECT_SIZE,
    EMPTY_RECORD_BYTE,
    EMPTY_ROSTER_BYTE,
    ENCOUNTER_STATE,
    ENGINE_REBUILT,
    FIELD_83_87,
    FIELDS_BY_NAME,
    FIELDS_BY_NAME_FOR,
    FILE_CACHE,
    FILE_CACHE_EMPTY,
    FILE_CACHE_RELOAD,
    FLAGS_FIRST,
    FLAGS_LAST,
    HEADER_ZEROED,
    ICON_SIZE,
    ICON_TABLE,
    INDOORS,
    INNATE_EFFECTS,
    INNATE_EFFECTS_CURSE,
    INNATE_EFFECTS_POOLS_OF_DARKNESS,
    INNATE_EFFECTS_SILVER_BLADES,
    INNATE_PAYLOAD,
    ITEM_AREA,
    ITEM_FIELDS_BY_NAME,
    ITEM_SIZE,
    ITEM_TAIL,
    ITM_OMITTED_WHEN_EMPTY,
    LATER_BEGUN_WORD,
    LATER_FLAGS_WORD,
    LATER_HEADER_COPIED,
    LATER_MODE_WORD,
    LATER_SCRIPT_REFILLED,
    LATER_TITLE_CONSTANTS,
    LATER_TITLE_DROPPED,
    LATER_TITLE_TRANSFORMED,
    LAYOUTS,
    NOT_AN_AREA,
    NPC_ICON_SLOTS,
    OUTDOOR_FACING,
    OUTDOOR_FACING_WHY,
    PALADIN_CLASS_BIT,
    PALADIN_SLOT,
    PARTY_FACING,
    PARTY_TABLE_SCRATCH,
    PARTY_X,
    PARTY_Y,
    POOL_OF_RADIANCE,
    POOLS_OF_DARKNESS,
    PORTRAIT_DRAWN,
    PORTRAIT_OFF,
    PORTRAIT_ON,
    PORTRAIT_SWITCH,
    PORTRAIT_SWITCH_WHY,
    RACE_COMBAT_EFFECTS,
    RACE_COMBAT_EFFECTS_CURSE,
    RACE_COMBAT_EFFECTS_POOLS_OF_DARKNESS,
    RACE_COMBAT_EFFECTS_SILVER_BLADES,
    RANGER_BIT_DOS,
    RANGER_BIT_NEUTRAL,
    RANGER_SLOT,
    RECORD_SIZE,
    ROSTER_STRIDE,
    SAVE0_BASE,
    SAVE0_SIZE,
    SAVE1_BASE,
    SAVE1_SIZE,
    SAVGAM_CONSTANTS_LATER,
    SAVGAM_MEASURED,
    SAVGAM_UNSOURCED,
    SAVGAM_UNSOURCED_LATER,
    SCRIPT_SCRATCH,
    SCROLL_BUNDLE_TYPE,
    SECRET_OF_THE_SILVER_BLADES,
    SHAPES,
    SLOT_AREA,
    SLOT_COUNT,
    SLOT_STRIDE,
    SLOT_TOTAL,
    TRANSFORMED,
    UNSUPPORTED_LOCATION,
    WRITE_CONSTANTS,
    WRITE_DERIVED_LATER,
    WRITE_DIRECT,
    WRITE_DROPPED,
    WRITE_TARGETS,
    WRITE_TRANSFORMED,
    WRITE_TRANSFORMED_LATER,
    WRITE_UNSOURCED,
    WRITE_UNSOURCED_LATER,
    WRITES,
    Any,
    CharacterRecord,
    Confidence,
    DosDeltas,
    DosIcon,
    DosIconTables,
    DosShape,
    DosShapeError,
    Field,
    IconParts,
    Iterable,
    Kind,
    NeutralCharacter,
    PortraitError,
    Provenance,
    SaveReport,
    Sequence,
    __all__,
    _ability_pair,
    _area_dax,
    _area_script,
    _clear_slot,
    _decode,
    _encode,
    _Fielded,
    _from_c64_class_traits,
    _icon_for,
    _innate_effects,
    _log,
    _note_word,
    _pair_bytes,
    _race_combat_effects,
    _read_ecl_dax,
    _resident_geo,
    _sibling,
    _sqrdata_number,
    _start_of_the_story,
    _where_the_party_is,
    areas,
    c64_codec,
    c64_icon_tables,
    c64_save,
    c64_title,
    c64_wall_triple,
    classcode,
    combat_byte,
    conversion_reason,
    dataclasses,
    dos_class_bits,
    dos_dax_number,
    dos_icon_tables,
    dos_savegame,
    dos_size,
    draws_sheet_portrait,
    field_disposition,
    games,
    hashlib,
    level_tables,
    logging,
    neutral,
    neutral_class_bits,
    neutral_menu,
    pathlib,
    retarget_reason,
    savgam_constants,
    savgam_unsourced,
    savgam_writes,
    savgam_zeroes,
    shape_for,
    shutil,
    tables_from_dos,
    tempfile,
    titles,
    traits,
    world_state,
    write_absent,
    write_constants,
    write_deltas,
    write_shape,
    write_targets,
)
