# Form implementation generated from reading ui file '/home/donald/src/wish/automap/actionbar.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActionBar(object):
    def setupUi(self, ActionBar):
        ActionBar.setObjectName("ActionBar")
        self.gridLayout = QtWidgets.QGridLayout(ActionBar)
        self.gridLayout.setContentsMargins(0, 4, 0, 2)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.watch_box = ElidingCheckBox(parent=ActionBar)
        self.watch_box.setObjectName("watch_box")
        self.gridLayout.addWidget(self.watch_box, 10, 0, 1, 1)
        self.note = QtWidgets.QLabel(parent=ActionBar)
        self.note.setText("")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.note.setFont(font)
        self.note.setWordWrap(True)
        self.note.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.note.setObjectName("note")
        self.gridLayout.addWidget(self.note, 10, 1, 1, 2)

        self.retranslateUi(ActionBar)

    def retranslateUi(self, ActionBar):
        _translate = QtCore.QCoreApplication.translate
        self.watch_box.setText(_translate("ActionBar", "Clear quickfight after a fight"))
        self.watch_box.setToolTip(_translate("ActionBar", "When a fight ends, take everyone off quickfight. Off by default: it writes to the running game on an edge you did not ask for"))
from automap.panel import ElidingCheckBox
