# Form implementation generated from reading ui file '/home/donald/src/wish/automap/bottomstrip.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BottomStrip(object):
    def setupUi(self, BottomStrip):
        BottomStrip.setObjectName("BottomStrip")
        self.box = QtWidgets.QVBoxLayout(BottomStrip)
        self.box.setContentsMargins(0, 4, 0, 0)
        self.box.setSpacing(2)
        self.box.setObjectName("box")
        self.row = QtWidgets.QHBoxLayout()
        self.row.setSpacing(16)
        self.row.setObjectName("row")
        self.where = ElidingLabel(parent=BottomStrip)
        self.where.setObjectName("where")
        self.row.addWidget(self.where)
        self.clock = ElidingLabel(parent=BottomStrip)
        self.clock.setObjectName("clock")
        self.row.addWidget(self.clock)
        self.area = ElidingLabel(parent=BottomStrip)
        self.area.setObjectName("area")
        self.row.addWidget(self.area)
        self.effects = ElidingLabel(parent=BottomStrip)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.effects.setFont(font)
        self.effects.setObjectName("effects")
        self.row.addWidget(self.effects)
        self.box.addLayout(self.row)

        self.retranslateUi(BottomStrip)

    def retranslateUi(self, BottomStrip):
        _translate = QtCore.QCoreApplication.translate
        self.where.setText(_translate("BottomStrip", "-"))
        self.clock.setText(_translate("BottomStrip", "-"))
        self.area.setText(_translate("BottomStrip", "-"))
        self.effects.setText(_translate("BottomStrip", "-"))
from automap.panel import ElidingLabel
