# Form implementation generated from reading ui file '/home/donald/src/wish/automap/card.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CharacterCard(object):
    def setupUi(self, CharacterCard):
        CharacterCard.setObjectName("CharacterCard")
        self.box = QtWidgets.QVBoxLayout(CharacterCard)
        self.box.setContentsMargins(8, 6, 8, 6)
        self.box.setSpacing(3)
        self.box.setObjectName("box")
        self.top = QtWidgets.QHBoxLayout()
        self.top.setObjectName("top")
        self.name = QtWidgets.QLabel(parent=CharacterCard)
        self.name.setText("")
        font = QtGui.QFont()
        font.setBold(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.top.addWidget(self.name)
        self.conditions = IconRow(parent=CharacterCard)
        self.conditions.setObjectName("conditions")
        self.top.addWidget(self.conditions)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top.addItem(spacerItem)
        self.combat = QtWidgets.QLabel(parent=CharacterCard)
        self.combat.setText("")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.combat.setFont(font)
        self.combat.setObjectName("combat")
        self.top.addWidget(self.combat)
        self.box.addLayout(self.top)
        self.klass_row = QtWidgets.QHBoxLayout()
        self.klass_row.setSpacing(4)
        self.klass_row.setObjectName("klass_row")
        self.klass = QtWidgets.QLabel(parent=CharacterCard)
        self.klass.setText("")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.klass.setFont(font)
        self.klass.setObjectName("klass")
        self.klass_row.addWidget(self.klass)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.klass_row.addItem(spacerItem1)
        self.quickfight = IconRow(parent=CharacterCard)
        self.quickfight.setObjectName("quickfight")
        self.klass_row.addWidget(self.quickfight, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.level_up = QtWidgets.QPushButton(parent=CharacterCard)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.level_up.setFont(font)
        self.level_up.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.level_up.setMinimumSize(QtCore.QSize(0, 18))
        self.level_up.setMaximumSize(QtCore.QSize(16777215, 18))
        self.level_up.setObjectName("level_up")
        self.klass_row.addWidget(self.level_up, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.box.addLayout(self.klass_row)
        self.bars_layout = QtWidgets.QVBoxLayout()
        self.bars_layout.setObjectName("bars_layout")
        self.box.addLayout(self.bars_layout)
        self.readied = QtWidgets.QLabel(parent=CharacterCard)
        self.readied.setText("")
        self.readied.setMinimumSize(QtCore.QSize(0, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.readied.setFont(font)
        self.readied.setObjectName("readied")
        self.box.addWidget(self.readied)
        self.effects = QtWidgets.QLabel(parent=CharacterCard)
        self.effects.setText("")
        self.effects.setMinimumSize(QtCore.QSize(0, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.effects.setFont(font)
        self.effects.setWordWrap(True)
        self.effects.setObjectName("effects")
        self.box.addWidget(self.effects)

        self.retranslateUi(CharacterCard)

    def retranslateUi(self, CharacterCard):
        _translate = QtCore.QCoreApplication.translate
        self.level_up.setText(_translate("CharacterCard", "Level up"))
from automap.panel import IconRow
