# Form implementation generated from reading ui file '/home/donald/src/wish/automap/commissions.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommissionsPanel(object):
    def setupUi(self, CommissionsPanel):
        CommissionsPanel.setObjectName("CommissionsPanel")
        self.outer = QtWidgets.QVBoxLayout(CommissionsPanel)
        self.outer.setContentsMargins(0, 0, 0, 0)
        self.outer.setSpacing(4)
        self.outer.setObjectName("outer")
        self.heading = QtWidgets.QLabel(parent=CommissionsPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.heading.setFont(font)
        self.heading.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.heading.setObjectName("heading")
        self.outer.addWidget(self.heading)
        self.scroll = QtWidgets.QScrollArea(parent=CommissionsPanel)
        self.scroll.setWidgetResizable(True)
        self.scroll.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll.setObjectName("scroll")
        self.inner = QtWidgets.QWidget()
        self.inner.setObjectName("inner")
        self.column = QtWidgets.QVBoxLayout(self.inner)
        self.column.setContentsMargins(8, 6, 8, 6)
        self.column.setSpacing(8)
        self.column.setObjectName("column")
        self.completed = QtWidgets.QLabel(parent=self.inner)
        self.completed.setText("")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.completed.setFont(font)
        self.completed.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.completed.setObjectName("completed")
        self.column.addWidget(self.completed)
        self.scroll.setWidget(self.inner)
        self.outer.addWidget(self.scroll)

        self.retranslateUi(CommissionsPanel)

    def retranslateUi(self, CommissionsPanel):
        _translate = QtCore.QCoreApplication.translate
        self.heading.setText(_translate("CommissionsPanel", "Commissions"))
