# Form implementation generated from reading ui file '/home/donald/src/wish/automap/fasttravelbar.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FastTravelBar(object):
    def setupUi(self, FastTravelBar):
        FastTravelBar.setObjectName("FastTravelBar")
        self.gridLayout = QtWidgets.QGridLayout(FastTravelBar)
        self.gridLayout.setContentsMargins(0, 2, 0, 2)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.combo = ElidingComboBox(parent=FastTravelBar)
        self.combo.setObjectName("combo")
        self.gridLayout.addWidget(self.combo, 0, 0, 1, 2)
        self.button = ElidingButton(parent=FastTravelBar)
        self.button.setEnabled(False)
        self.button.setObjectName("button")
        self.gridLayout.addWidget(self.button, 0, 2, 1, 1)
        self.back_button = ElidingButton(parent=FastTravelBar)
        self.back_button.setEnabled(False)
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 0, 3, 1, 1)
        self.note = QtWidgets.QLabel(parent=FastTravelBar)
        self.note.setText("")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.note.setFont(font)
        self.note.setWordWrap(True)
        self.note.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.note.setObjectName("note")
        self.gridLayout.addWidget(self.note, 1, 0, 1, 4)

        self.retranslateUi(FastTravelBar)

    def retranslateUi(self, FastTravelBar):
        _translate = QtCore.QCoreApplication.translate
        self.button.setText(_translate("FastTravelBar", "Fast Travel"))
        self.back_button.setText(_translate("FastTravelBar", "Travel Back"))
from automap.panel import ElidingButton, ElidingComboBox
