# Form implementation generated from reading ui file '/home/donald/src/wish/automap/notes.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NotesPanel(object):
    def setupUi(self, NotesPanel):
        NotesPanel.setObjectName("NotesPanel")
        self.outer = QtWidgets.QVBoxLayout(NotesPanel)
        self.outer.setContentsMargins(0, 0, 0, 0)
        self.outer.setSpacing(4)
        self.outer.setObjectName("outer")
        self.heading = QtWidgets.QLabel(parent=NotesPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.heading.setFont(font)
        self.heading.setObjectName("heading")
        self.outer.addWidget(self.heading)
        self.list = QtWidgets.QListWidget(parent=NotesPanel)
        self.list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.list.setIconSize(QtCore.QSize(13, 13))
        self.list.setWordWrap(True)
        self.list.setObjectName("list")
        self.outer.addWidget(self.list)

        self.retranslateUi(NotesPanel)

    def retranslateUi(self, NotesPanel):
        _translate = QtCore.QCoreApplication.translate
        self.heading.setText(_translate("NotesPanel", "Notes"))
