# Form implementation generated from reading ui file 'automap/noteeditor.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NotePopover(object):
    def setupUi(self, NotePopover):
        NotePopover.setObjectName("NotePopover")
        self.outer_layout = QtWidgets.QVBoxLayout(NotePopover)
        self.outer_layout.setContentsMargins(8, 6, 8, 6)
        self.outer_layout.setSpacing(4)
        self.outer_layout.setObjectName("outer_layout")
        self.head = QtWidgets.QLabel(parent=NotePopover)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.head.setFont(font)
        self.head.setObjectName("head")
        self.outer_layout.addWidget(self.head)
        self.picker = QtWidgets.QHBoxLayout()
        self.picker.setSpacing(2)
        self.picker.setObjectName("picker")
        self.outer_layout.addLayout(self.picker)
        self.field = QtWidgets.QLineEdit(parent=NotePopover)
        self.field.setObjectName("field")
        self.outer_layout.addWidget(self.field)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setSpacing(4)
        self.buttons.setObjectName("buttons")
        self.remove = QtWidgets.QPushButton(parent=NotePopover)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.remove.setFont(font)
        self.remove.setObjectName("remove")
        self.buttons.addWidget(self.remove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttons.addItem(spacerItem)
        self.keep = QtWidgets.QPushButton(parent=NotePopover)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.keep.setFont(font)
        self.keep.setDefault(True)
        self.keep.setObjectName("keep")
        self.buttons.addWidget(self.keep)
        self.outer_layout.addLayout(self.buttons)
        self.hint = QtWidgets.QLabel(parent=NotePopover)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hint.setFont(font)
        self.hint.setObjectName("hint")
        self.outer_layout.addWidget(self.hint)

        self.retranslateUi(NotePopover)
        QtCore.QMetaObject.connectSlotsByName(NotePopover)

    def retranslateUi(self, NotePopover):
        _translate = QtCore.QCoreApplication.translate
        self.field.setPlaceholderText(_translate("NotePopover", "a few words, or none"))
        self.remove.setText(_translate("NotePopover", "Delete"))
        self.remove.setToolTip(_translate("NotePopover", "remove this note from the square"))
        self.keep.setText(_translate("NotePopover", "Keep"))
        self.hint.setText(_translate("NotePopover", "Enter keeps it, Escape leaves it alone"))
