# Form implementation generated from reading ui file '/home/donald/src/wish/automap/roster.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RosterPanel(object):
    def setupUi(self, RosterPanel):
        RosterPanel.setObjectName("RosterPanel")
        self.outer = QtWidgets.QVBoxLayout(RosterPanel)
        self.outer.setContentsMargins(0, 0, 0, 0)
        self.outer.setSpacing(4)
        self.outer.setObjectName("outer")
        self.heading = QtWidgets.QLabel(parent=RosterPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.heading.setFont(font)
        self.heading.setObjectName("heading")
        self.outer.addWidget(self.heading)
        self.scroll = QtWidgets.QScrollArea(parent=RosterPanel)
        self.scroll.setWidgetResizable(True)
        self.scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll.setObjectName("scroll")
        self.inner = QtWidgets.QWidget()
        self.inner.setObjectName("inner")
        self.column = QtWidgets.QVBoxLayout(self.inner)
        self.column.setContentsMargins(0, 0, 0, 0)
        self.column.setSpacing(6)
        self.column.setObjectName("column")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.column.addItem(spacerItem)
        self.scroll.setWidget(self.inner)
        self.outer.addWidget(self.scroll)

        self.retranslateUi(RosterPanel)

    def retranslateUi(self, RosterPanel):
        _translate = QtCore.QCoreApplication.translate
        self.heading.setText(_translate("RosterPanel", "Party"))
