# Form implementation generated from reading ui file '/home/donald/src/wish/automap/window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AutomapWindow(object):
    def setupUi(self, AutomapWindow):
        AutomapWindow.setObjectName("AutomapWindow")
        self.centre = QtWidgets.QWidget(parent=AutomapWindow)
        self.centre.setObjectName("centre")
        self.grid = QtWidgets.QGridLayout(self.centre)
        self.grid.setObjectName("grid")
        self.roster_placeholder = QtWidgets.QWidget(parent=self.centre)
        self.roster_placeholder.setObjectName("roster_placeholder")
        self.grid.addWidget(self.roster_placeholder, 0, 0, 1, 1)
        self.map_column = QtWidgets.QWidget(parent=self.centre)
        self.map_column.setObjectName("map_column")
        self.map_column_layout = QtWidgets.QVBoxLayout(self.map_column)
        self.map_column_layout.setContentsMargins(0, 0, 0, 0)
        self.map_column_layout.setSpacing(4)
        self.map_column_layout.setObjectName("map_column_layout")
        self.stack = QtWidgets.QStackedWidget(parent=self.map_column)
        self.stack.setObjectName("stack")
        self.map_column_layout.addWidget(self.stack, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.actions_bar_placeholder = QtWidgets.QWidget(parent=self.map_column)
        self.actions_bar_placeholder.setObjectName("actions_bar_placeholder")
        self.map_column_layout.addWidget(self.actions_bar_placeholder, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.fasttravel_bar_placeholder = QtWidgets.QWidget(parent=self.map_column)
        self.fasttravel_bar_placeholder.setObjectName("fasttravel_bar_placeholder")
        self.map_column_layout.addWidget(self.fasttravel_bar_placeholder, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.map_column_layout.addItem(spacerItem)
        self.grid.addWidget(self.map_column, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.side = QtWidgets.QWidget(parent=self.centre)
        self.side.setMaximumSize(QtCore.QSize(460, 16777215))
        self.side.setObjectName("side")
        self.side_layout = QtWidgets.QVBoxLayout(self.side)
        self.side_layout.setContentsMargins(0, 0, 0, 0)
        self.side_layout.setSpacing(6)
        self.side_layout.setObjectName("side_layout")
        self.side_splitter = QtWidgets.QSplitter(parent=self.side)
        self.side_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.side_splitter.setObjectName("side_splitter")
        self.notes_placeholder = QtWidgets.QWidget(parent=self.side_splitter)
        self.notes_placeholder.setObjectName("notes_placeholder")
        self.commissions_placeholder = QtWidgets.QWidget(parent=self.side_splitter)
        self.commissions_placeholder.setObjectName("commissions_placeholder")
        self.messages_placeholder = QtWidgets.QWidget(parent=self.side_splitter)
        self.messages_placeholder.setObjectName("messages_placeholder")
        self.side_layout.addWidget(self.side_splitter)
        self.grid.addWidget(self.side, 0, 2, 1, 1)
        self.strip_placeholder = QtWidgets.QWidget(parent=self.centre)
        self.strip_placeholder.setObjectName("strip_placeholder")
        self.grid.addWidget(self.strip_placeholder, 1, 0, 1, 3)
        self.strength_label = QtWidgets.QLabel(parent=self.centre)
        self.strength_label.setStyleSheet("color: #5c6b7a")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.strength_label.setFont(font)
        self.strength_label.setObjectName("strength_label")
        self.grid.addWidget(self.strength_label, 2, 0, 1, 3)
        AutomapWindow.setCentralWidget(self.centre)
        self.statusbar = QtWidgets.QStatusBar(parent=AutomapWindow)
        self.statusbar.setObjectName("statusbar")
        AutomapWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AutomapWindow)
        QtCore.QMetaObject.connectSlotsByName(AutomapWindow)

    def retranslateUi(self, AutomapWindow):
        _translate = QtCore.QCoreApplication.translate
        AutomapWindow.setWindowTitle(_translate("AutomapWindow", "Pool of Radiance - automap"))
        self.strength_label.setText(_translate("AutomapWindow", "party strength --"))
        self.strength_label.setToolTip(_translate("AutomapWindow", "How big a random encounter is. Not readable yet."))
