# Form implementation generated from reading ui file 'automap/warpbar.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WarpBar(object):
    def setupUi(self, WarpBar):
        WarpBar.setObjectName("WarpBar")
        self.gridLayout = QtWidgets.QGridLayout(WarpBar)
        self.gridLayout.setContentsMargins(0, 2, 0, 2)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.combo = ElidingComboBox(parent=WarpBar)
        self.combo.setObjectName("combo")
        self.gridLayout.addWidget(self.combo, 0, 0, 1, 2)
        self.button = ElidingButton(parent=WarpBar)
        self.button.setEnabled(False)
        self.button.setObjectName("button")
        self.gridLayout.addWidget(self.button, 0, 2, 1, 1)
        self.back_button = ElidingButton(parent=WarpBar)
        self.back_button.setEnabled(False)
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 0, 3, 1, 1)
        self.note = QtWidgets.QLabel(parent=WarpBar)
        self.note.setText("")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.note.setFont(font)
        self.note.setWordWrap(True)
        self.note.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.note.setObjectName("note")
        self.gridLayout.addWidget(self.note, 1, 0, 1, 4)

        self.retranslateUi(WarpBar)

    def retranslateUi(self, WarpBar):
        _translate = QtCore.QCoreApplication.translate
        self.button.setText(_translate("WarpBar", "Fast Travel"))
        self.back_button.setText(_translate("WarpBar", "Travel Back"))
from automap.panel import ElidingButton, ElidingComboBox
