#!/usr/bin/env bash
# c <command...> : send one line to the running session driver
python3 - "$@" <<'PY'
import socket,sys
s=socket.create_connection(("127.0.0.1",6600),timeout=300); s.settimeout(300)
s.sendall((" ".join(sys.argv[1:])+"\n").encode())
out=b""
while True:
    d=s.recv(65536)
    if not d: break
    out+=d
sys.stdout.write(out.decode("latin1"))
PY
